import json
import re

# We will generate all 195 sovereign countries
# Let's ensure every single sovereign nation is included with full missional metadata

EUROPE_COUNTRIES = [
    {"id": "alb", "code": "AL", "code3": "ALB", "name": "Albania", "flag": "🇦🇱", "continent": "Europe", "population": 2780000,
     "dominantReligions": [{"religion": "Islam", "percentage": 56.7}, {"religion": "Christianity (Catholic)", "percentage": 10.0}, {"religion": "Christianity (Orthodox)", "percentage": 6.8}, {"religion": "Secular", "percentage": 26.5}],
     "christianPercentage": 17.0, "evangelicalPercentage": 0.6, "unreachedPopulationPercentage": 62.0, "unreachedPeopleGroupsCount": 3, "securityLevel": "Low",
     "primaryLanguages": ["Albanian", "Greek"], "capitalCity": "Tirana", "isIn1040Window": False, "activeMissionariesCount": 45, "activePrayerWarriorsCount": 890,
     "description": "Former officially atheist state where freedom of worship now enables vigorous church planting across mountainous towns.",
     "prayerPoints": ["Spiritual awakening in post-communist towns", "Church planting in isolated northern valleys", "Equipping young pastors"],
     "missionOpportunities": ["University student ministry in Tirana", "Youth summer camps and English clubs"]},
    
    {"id": "and", "code": "AD", "code3": "AND", "name": "Andorra", "flag": "🇦🇩", "continent": "Europe", "population": 80000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 88.0}, {"religion": "Secular", "percentage": 10.0}, {"religion": "Other", "percentage": 2.0}],
     "christianPercentage": 89.0, "evangelicalPercentage": 0.5, "unreachedPopulationPercentage": 5.0, "unreachedPeopleGroupsCount": 1, "securityLevel": "Low",
     "primaryLanguages": ["Catalan", "Spanish", "French"], "capitalCity": "Andorra la Vella", "isIn1040Window": False, "activeMissionariesCount": 4, "activePrayerWarriorsCount": 140,
     "description": "Pyrenean mountain nation with a rich Catholic heritage and growing need for evangelical discipleship.",
     "prayerPoints": ["Revival across Pyrenean valleys", "Growth of evangelical fellowships in Andorra la Vella"],
     "missionOpportunities": ["Winter sports outdoor ministry", "Catalan scripture distribution"]},

    {"id": "aut", "code": "AT", "code3": "AUT", "name": "Austria", "flag": "🇦🇹", "continent": "Europe", "population": 9100000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 55.2}, {"religion": "Secular", "percentage": 22.4}, {"religion": "Islam", "percentage": 8.3}, {"religion": "Other", "percentage": 14.1}],
     "christianPercentage": 64.0, "evangelicalPercentage": 0.9, "unreachedPopulationPercentage": 9.0, "unreachedPeopleGroupsCount": 5, "securityLevel": "Low",
     "primaryLanguages": ["German", "Turkish", "Serbo-Croatian"], "capitalCity": "Vienna", "isIn1040Window": False, "activeMissionariesCount": 65, "activePrayerWarriorsCount": 1300,
     "description": "Heart of Central Europe. While retaining historic cathedral architecture, less than 1% are evangelical Christians.",
     "prayerPoints": ["Spiritual renewal in Austrian university students", "Gospel multiplication among Turkish and Afghan diaspora in Vienna", "Evangelical unity across free churches"],
     "missionOpportunities": ["Diaspora refugee integration cafes", "Campus discipleship at University of Vienna"]},

    {"id": "blr", "code": "BY", "code3": "BLR", "name": "Belarus", "flag": "🇧🇾", "continent": "Europe", "population": 9200000,
     "dominantReligions": [{"religion": "Christianity (Orthodox)", "percentage": 73.0}, {"religion": "Christianity (Catholic)", "percentage": 12.0}, {"religion": "Secular", "percentage": 12.5}, {"religion": "Christianity (Evangelical)", "percentage": 2.5}],
     "christianPercentage": 87.5, "evangelicalPercentage": 2.0, "unreachedPopulationPercentage": 3.0, "unreachedPeopleGroupsCount": 2, "securityLevel": "High",
     "primaryLanguages": ["Belarusian", "Russian"], "capitalCity": "Minsk", "isIn1040Window": False, "activeMissionariesCount": 35, "activePrayerWarriorsCount": 1100,
     "description": "Known for resilient evangelical churches that grew under Soviet persecution and continue faithful witness.",
     "prayerPoints": ["Freedom to worship and build churches", "Revival among university students in Minsk", "Endurance for church leaders"],
     "missionOpportunities": ["Youth rehabilitation centers", "Children's summer camps"]},

    {"id": "bel", "code": "BE", "code3": "BEL", "name": "Belgium", "flag": "🇧🇪", "continent": "Europe", "population": 11690000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 54.0}, {"religion": "Secular", "percentage": 31.0}, {"religion": "Islam", "percentage": 7.6}, {"religion": "Other", "percentage": 7.4}],
     "christianPercentage": 59.0, "evangelicalPercentage": 1.4, "unreachedPopulationPercentage": 11.0, "unreachedPeopleGroupsCount": 14, "securityLevel": "Low",
     "primaryLanguages": ["Dutch (Flemish)", "French", "German"], "capitalCity": "Brussels", "isIn1040Window": False, "activeMissionariesCount": 70, "activePrayerWarriorsCount": 1400,
     "description": "Seat of the European Union. Immigrant African and Latin churches are flourishing in Brussels amidst secular society.",
     "prayerPoints": ["Spiritual awakening in Flanders and Wallonia", "Outreach among North African communities in Brussels and Antwerp", "Christian unity across language divides"],
     "missionOpportunities": ["EU diplomatic and policy worker ministry", "Diaspora cafe outreach"]},

    {"id": "bih", "code": "BA", "code3": "BIH", "name": "Bosnia and Herzegovina", "flag": "🇧🇦", "continent": "Europe", "population": 3200000,
     "dominantReligions": [{"religion": "Islam (Sunni)", "percentage": 50.7}, {"religion": "Christianity (Serb Orthodox)", "percentage": 30.7}, {"religion": "Christianity (Croat Catholic)", "percentage": 15.2}, {"religion": "Other", "percentage": 3.4}],
     "christianPercentage": 46.0, "evangelicalPercentage": 0.1, "unreachedPopulationPercentage": 52.0, "unreachedPeopleGroupsCount": 4, "securityLevel": "Low",
     "primaryLanguages": ["Bosnian", "Croatian", "Serbian"], "capitalCity": "Sarajevo", "isIn1040Window": False, "activeMissionariesCount": 25, "activePrayerWarriorsCount": 650,
     "description": "Post-war nation where evangelical churches are uniquely positioned to bridge deep historic ethnic and religious divides.",
     "prayerPoints": ["Reconciliation and lasting peace between Bosniak, Serb, and Croat peoples", "Gospel breakthrough among the 1.6M Bosniak Muslim population", "Raising young local church planters in Sarajevo and Mostar"],
     "missionOpportunities": ["Youth reconciliation centers and English teaching", "Church planting in small towns"]},

    {"id": "bgr", "code": "BG", "code3": "BGR", "name": "Bulgaria", "flag": "🇧🇬", "continent": "Europe", "population": 6450000,
     "dominantReligions": [{"religion": "Christianity (Bulgarian Orthodox)", "percentage": 76.0}, {"religion": "Islam (Turk/Pomak)", "percentage": 10.0}, {"religion": "Secular / Other", "percentage": 14.0}],
     "christianPercentage": 78.0, "evangelicalPercentage": 2.2, "unreachedPopulationPercentage": 12.0, "unreachedPeopleGroupsCount": 6, "securityLevel": "Low",
     "primaryLanguages": ["Bulgarian", "Turkish", "Romani"], "capitalCity": "Sofia", "isIn1040Window": False, "activeMissionariesCount": 55, "activePrayerWarriorsCount": 1200,
     "description": "Experiencing dramatic evangelical revivals among the marginalized Roma (Gypsy) community, while Turkish and Pomak Muslims remain in need of pioneers.",
     "prayerPoints": ["Spiritual awakening among Turkish and Pomak Muslim minorities in the Rhodope mountains", "Equipping Roma evangelists to reach other Balkan nations", "Revival in historic Orthodox church communities"],
     "missionOpportunities": ["Roma community literacy and church planting", "Turkish-language ministry in Kardzhali and Shumen"]},

    {"id": "hrv", "code": "HR", "code3": "HRV", "name": "Croatia", "flag": "🇭🇷", "continent": "Europe", "population": 3870000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 79.0}, {"religion": "Christianity (Orthodox)", "percentage": 3.3}, {"religion": "Secular / Other", "percentage": 17.7}],
     "christianPercentage": 83.0, "evangelicalPercentage": 0.4, "unreachedPopulationPercentage": 3.0, "unreachedPeopleGroupsCount": 2, "securityLevel": "Low",
     "primaryLanguages": ["Croatian"], "capitalCity": "Zagreb", "isIn1040Window": False, "activeMissionariesCount": 35, "activePrayerWarriorsCount": 780,
     "description": "Adriatic nation with deep Catholic roots where evangelical fellowships are actively planting churches in urban centers and university cities.",
     "prayerPoints": ["Fresh personal encounter with Christ for Croatian youth", "Growth of church planting networks along the Dalmatian coast and Slavonia", "Christian counseling and family support initiatives"],
     "missionOpportunities": ["University campus ministry in Zagreb, Split, and Rijeka", "Creative arts and media outreach"]},

    {"id": "cze", "code": "CZ", "code3": "CZE", "name": "Czech Republic", "flag": "🇨🇿", "continent": "Europe", "population": 10500000,
     "dominantReligions": [{"religion": "No Religion / Atheist", "percentage": 78.0}, {"religion": "Christianity (Catholic)", "percentage": 10.4}, {"religion": "Christianity (Protestant)", "percentage": 1.5}, {"religion": "Other", "percentage": 10.1}],
     "christianPercentage": 12.0, "evangelicalPercentage": 0.8, "unreachedPopulationPercentage": 78.0, "unreachedPeopleGroupsCount": 4, "securityLevel": "Low",
     "primaryLanguages": ["Czech"], "capitalCity": "Prague", "isIn1040Window": False, "activeMissionariesCount": 85, "activePrayerWarriorsCount": 1600,
     "description": "Historic land of Jan Hus and the Moravian revival, now considered one of the most secular and atheist societies in Europe.",
     "prayerPoints": ["Re-igniting the spiritual fire of the Moravian revival and Jan Hus", "Spiritual breakthrough in highly secular academic and artistic communities", "Multiplying simple church communities in Prague and Brno"],
     "missionOpportunities": ["Cafe churches and intellectual apologetics forums", "English and sports camps for young people"]},

    {"id": "dnk", "code": "DK", "code3": "DNK", "name": "Denmark", "flag": "🇩🇰", "continent": "Europe", "population": 5930000,
     "dominantReligions": [{"religion": "Christianity (Lutheran)", "percentage": 72.1}, {"religion": "No Religion / Secular", "percentage": 22.0}, {"religion": "Islam", "percentage": 4.4}, {"religion": "Other", "percentage": 1.5}],
     "christianPercentage": 74.0, "evangelicalPercentage": 3.5, "unreachedPopulationPercentage": 6.0, "unreachedPeopleGroupsCount": 5, "securityLevel": "Low",
     "primaryLanguages": ["Danish", "English"], "capitalCity": "Copenhagen", "isIn1040Window": False, "activeMissionariesCount": 60, "activePrayerWarriorsCount": 1400,
     "description": "Historic Scandinavian Protestant heritage. Free church movements and immigrant fellowships in Copenhagen are experiencing fresh energy.",
     "prayerPoints": ["Spiritual awakening in Danish society and university campuses", "Effective outreach to immigrant Muslim communities in Copenhagen and Aarhus", "Mobilizing young Danes for international missions"],
     "missionOpportunities": ["Innovative urban church planting in Copenhagen", "Diaspora ministry among Middle Eastern refugees"]},

    {"id": "est", "code": "EE", "code3": "EST", "name": "Estonia", "flag": "🇪🇪", "continent": "Europe", "population": 1360000,
     "dominantReligions": [{"religion": "No Religion / Secular", "percentage": 60.0}, {"religion": "Christianity (Orthodox)", "percentage": 16.0}, {"religion": "Christianity (Lutheran)", "percentage": 10.0}, {"religion": "Christianity (Evangelical / Baptist)", "percentage": 2.5}, {"religion": "Other", "percentage": 11.5}],
     "christianPercentage": 29.0, "evangelicalPercentage": 4.8, "unreachedPopulationPercentage": 60.0, "unreachedPeopleGroupsCount": 2, "securityLevel": "Low",
     "primaryLanguages": ["Estonian", "Russian"], "capitalCity": "Tallinn", "isIn1040Window": False, "activeMissionariesCount": 35, "activePrayerWarriorsCount": 850,
     "description": "Tech-forward Baltic nation with a strong history of Baptist and Methodist revivals. Youth prayer movements are contending for national revival.",
     "prayerPoints": ["Spiritual breakthrough across highly secular tech and digital culture", "Reconciliation and unity between Estonian and Russian-speaking churches", "Empowering young evangelists in Tallinn and Tartu"],
     "missionOpportunities": ["Digital evangelism and faith-and-tech incubators", "Youth leadership academies"]},

    {"id": "fin", "code": "FI", "code3": "FIN", "name": "Finland", "flag": "🇫🇮", "continent": "Europe", "population": 5560000,
     "dominantReligions": [{"religion": "Christianity (Lutheran)", "percentage": 65.2}, {"religion": "No Religion / Secular", "percentage": 32.0}, {"religion": "Christianity (Orthodox / Free Churches)", "percentage": 2.8}],
     "christianPercentage": 68.0, "evangelicalPercentage": 12.0, "unreachedPopulationPercentage": 3.0, "unreachedPeopleGroupsCount": 3, "securityLevel": "Low",
     "primaryLanguages": ["Finnish", "Swedish", "Sámi"], "capitalCity": "Helsinki", "isIn1040Window": False, "activeMissionariesCount": 110, "activePrayerWarriorsCount": 2400,
     "description": "Home to active prayer and missionary sending societies (Fida International) sending workers to unreached nations across Asia and Africa.",
     "prayerPoints": ["Revival of deep biblical faith in Lutheran parishes and free churches", "Spiritual witness among youth facing mental health struggles", "Continued sending of Finnish missionaries to the 10/40 window"],
     "missionOpportunities": ["Arctic and Lapland Sámi youth discipleship", "Cross-cultural missionary training"]},

    {"id": "fra", "code": "FR", "code3": "FRA", "name": "France", "flag": "🇫🇷", "continent": "Europe", "population": 68000000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 47.0}, {"religion": "No Religion / Secular", "percentage": 40.0}, {"religion": "Islam (Maghrebi/Turkish)", "percentage": 9.0}, {"religion": "Christianity (Evangelical/Protestant)", "percentage": 3.0}, {"religion": "Other", "percentage": 1.0}],
     "christianPercentage": 50.0, "evangelicalPercentage": 1.8, "unreachedPopulationPercentage": 12.0, "unreachedPeopleGroupsCount": 28, "securityLevel": "Low",
     "primaryLanguages": ["French", "Arabic", "Breton", "Occitan"], "capitalCity": "Paris", "isIn1040Window": False, "activeMissionariesCount": 310, "activePrayerWarriorsCount": 6800,
     "description": "Land of the Huguenots. Evangelical churches are growing steadily, especially in multi-ethnic Parisian suburbs and provincial cities.",
     "prayerPoints": ["Spiritual breakthrough against militant secularism (laïcité)", "Rapid church planting in over 30,000 French villages without an evangelical witness", "Gospel awakening among the 6 million North African and Turkish Muslims in France"],
     "missionOpportunities": ["Pioneer church planting in provincial France (1 per 10,000 goal)", "Diaspora and immigrant banlieue youth ministries", "University student discipleship in Paris, Lyon, and Toulouse"]},

    {"id": "deu", "code": "DE", "code3": "DEU", "name": "Germany", "flag": "🇩🇪", "continent": "Europe", "population": 84400000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 24.8}, {"religion": "Christianity (Protestant/EKD)", "percentage": 22.6}, {"religion": "No Religion / Secular", "percentage": 43.8}, {"religion": "Islam (Turkish/Arab)", "percentage": 6.8}, {"religion": "Christianity (Evangelical/Free Churches)", "percentage": 2.0}],
     "christianPercentage": 49.4, "evangelicalPercentage": 2.5, "unreachedPopulationPercentage": 9.5, "unreachedPeopleGroupsCount": 24, "securityLevel": "Low",
     "primaryLanguages": ["German", "Turkish", "Arabic", "Russian"], "capitalCity": "Berlin", "isIn1040Window": False, "activeMissionariesCount": 420, "activePrayerWarriorsCount": 8500,
     "description": "Birthplace of the Reformation (Martin Luther). Today, vital prayer houses (Gebetshaus Augsburg) and free church plants are contending for national revival.",
     "prayerPoints": ["Spiritual re-awakening in the secularized eastern states (former East Germany)", "Gospel breakthrough among 4 million Turkish and 1 million Syrian/Afghan diaspora", "Unity and bold evangelism among evangelical and charismatics"],
     "missionOpportunities": ["24/7 prayer house initiatives and worship schools", "Refugee diaspora integration and discipleship in Berlin and Ruhr Valley", "Youth university campus ministry"]},

    {"id": "grc", "code": "GR", "code3": "GRC", "name": "Greece", "flag": "🇬🇷", "continent": "Europe", "population": 10400000,
     "dominantReligions": [{"religion": "Christianity (Greek Orthodox)", "percentage": 90.0}, {"religion": "No Religion / Secular", "percentage": 6.0}, {"religion": "Islam (Thracian / Expat)", "percentage": 3.0}, {"religion": "Christianity (Evangelical/Catholic)", "percentage": 1.0}],
     "christianPercentage": 91.0, "evangelicalPercentage": 0.4, "unreachedPopulationPercentage": 4.5, "unreachedPeopleGroupsCount": 5, "securityLevel": "Low",
     "primaryLanguages": ["Greek", "Albanian", "Turkish"], "capitalCity": "Athens", "isIn1040Window": False, "activeMissionariesCount": 65, "activePrayerWarriorsCount": 1400,
     "description": "Where Paul preached at Mars Hill and planted churches in Corinth and Philippi. Today evangelical believers passionately reach refugees from the Middle East.",
     "prayerPoints": ["Personal spiritual revival and love for Scripture within the Orthodox community", "Blessing and fruitfulness for refugee relief ministries in Athens and Lesvos", "Gospel breakthrough among Thracian Pomak Muslims in northern Greece"],
     "missionOpportunities": ["Middle East and Afghan refugee care and church planting in Athens", "Island outreach and university student ministry in Thessaloniki"]},

    {"id": "vat", "code": "VA", "code3": "VAT", "name": "Holy See (Vatican City)", "flag": "🇻🇦", "continent": "Europe", "population": 800,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 100.0}],
     "christianPercentage": 100.0, "evangelicalPercentage": 1.0, "unreachedPopulationPercentage": 0.0, "unreachedPeopleGroupsCount": 0, "securityLevel": "Low",
     "primaryLanguages": ["Latin", "Italian"], "capitalCity": "Vatican City", "isIn1040Window": False, "activeMissionariesCount": 10, "activePrayerWarriorsCount": 450,
     "description": "Sovereign city-state and administrative center of the Roman Catholic Church, influencing over 1.3 billion adherents worldwide.",
     "prayerPoints": ["Biblical clarity, purity of the Gospel of Grace, and integrity across church leadership globally", "Spiritual renewal of faith in Jesus Christ across Catholic communities everywhere"],
     "missionOpportunities": ["Inter-denominational prayer dialogue for global evangelization"]},

    {"id": "hun", "code": "HU", "code3": "HUN", "name": "Hungary", "flag": "🇭🇺", "continent": "Europe", "population": 9600000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 50.0}, {"religion": "Christianity (Reformed/Protestant)", "percentage": 16.0}, {"religion": "No Religion / Secular", "percentage": 30.0}, {"religion": "Other", "percentage": 4.0}],
     "christianPercentage": 66.0, "evangelicalPercentage": 2.8, "unreachedPopulationPercentage": 5.0, "unreachedPeopleGroupsCount": 3, "securityLevel": "Low",
     "primaryLanguages": ["Hungarian", "Romani", "German"], "capitalCity": "Budapest", "isIn1040Window": False, "activeMissionariesCount": 65, "activePrayerWarriorsCount": 1350,
     "description": "Historic Christian nation with strong Reformed and Catholic heritage, witnessing growing evangelical movements among university youth and Roma.",
     "prayerPoints": ["Deep personal spiritual renewal to match historic Christian identity", "Vibrant church multiplication in Roma communities across northeastern Hungary", "Sending Hungarian missionaries to Central Europe and the Balkans"],
     "missionOpportunities": ["Roma village education and church planting", "University discipleship in Budapest and Debrecen"]},

    {"id": "isl", "code": "IS", "code3": "ISL", "name": "Iceland", "flag": "🇮🇸", "continent": "Europe", "population": 390000,
     "dominantReligions": [{"religion": "Christianity (Lutheran)", "percentage": 62.0}, {"religion": "No Religion / Secular", "percentage": 28.0}, {"religion": "Christianity (Catholic / Free Church)", "percentage": 7.0}, {"religion": "Other", "percentage": 3.0}],
     "christianPercentage": 69.0, "evangelicalPercentage": 3.8, "unreachedPopulationPercentage": 2.0, "unreachedPeopleGroupsCount": 1, "securityLevel": "Low",
     "primaryLanguages": ["Icelandic", "English"], "capitalCity": "Reykjavík", "isIn1040Window": False, "activeMissionariesCount": 12, "activePrayerWarriorsCount": 320,
     "description": "North Atlantic island nation with a proud heritage of faith, now experiencing a generation of youth seeking authentic spiritual reality in Christ.",
     "prayerPoints": ["Spiritual awakening in Reykjavík and coastal fishing communities", "Renewal of prayer and discipleship in young families", "Outreach to international workers and immigrants in Iceland"],
     "missionOpportunities": ["Youth worship and media ministries", "Immigrant fellowship planting in Reykjavík"]},

    {"id": "irl", "code": "IE", "code3": "IRL", "name": "Ireland", "flag": "🇮🇪", "continent": "Europe", "population": 5200000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 69.0}, {"religion": "No Religion / Secular", "percentage": 20.0}, {"religion": "Christianity (Protestant/Evangelical/Orthodox)", "percentage": 8.0}, {"religion": "Other", "percentage": 3.0}],
     "christianPercentage": 77.0, "evangelicalPercentage": 2.2, "unreachedPopulationPercentage": 4.0, "unreachedPeopleGroupsCount": 3, "securityLevel": "Low",
     "primaryLanguages": ["English", "Irish (Gaeilge)"], "capitalCity": "Dublin", "isIn1040Window": False, "activeMissionariesCount": 95, "activePrayerWarriorsCount": 2100,
     "description": "Land of Saint Patrick and Columba who once evangelized Europe. Rapid secularization is countered by exciting new church plants and prayer initiatives.",
     "prayerPoints": ["Re-awakening the missionary spirit of Saint Patrick in Irish youth", "Healing from past institutional church wounds and rediscovery of Jesus", "Church planting across rural towns and tech hubs in Dublin"],
     "missionOpportunities": ["Tech professional marketplace ministry in Dublin's Silicon Docks", "Pioneer church planting in rural western counties"]},

    {"id": "ita", "code": "IT", "code3": "ITA", "name": "Italy", "flag": "🇮🇹", "continent": "Europe", "population": 58800000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 75.0}, {"religion": "No Religion / Secular", "percentage": 19.0}, {"religion": "Islam", "percentage": 4.5}, {"religion": "Christianity (Evangelical/Waldensian/Pentecostal)", "percentage": 1.5}],
     "christianPercentage": 76.5, "evangelicalPercentage": 1.2, "unreachedPopulationPercentage": 8.0, "unreachedPeopleGroupsCount": 16, "securityLevel": "Low",
     "primaryLanguages": ["Italian", "Sicilian", "Sardinian", "Napolitan"], "capitalCity": "Rome", "isIn1040Window": False, "activeMissionariesCount": 210, "activePrayerWarriorsCount": 4600,
     "description": "Where Paul wrote Romans and finished his race. Despite historic religious heritage, less than 1.5% are evangelical, with over 70% of Italian towns having no evangelical church.",
     "prayerPoints": ["Pioneer church planting in thousands of unchurched Italian towns and villages", "Spiritual awakening among university students in Rome, Milan, and Bologna", "Gospel outreach to the large North African and South Asian immigrant communities"],
     "missionOpportunities": ["Church planting teams in southern Italy (Campania, Calabria, Sicily)", "Refugee transit care and church planting in port cities", "University campus ministry"]},

    {"id": "lva", "code": "LV", "code3": "LVA", "name": "Latvia", "flag": "🇱🇻", "continent": "Europe", "population": 1880000,
     "dominantReligions": [{"religion": "Christianity (Lutheran)", "percentage": 36.0}, {"religion": "Christianity (Catholic)", "percentage": 25.0}, {"religion": "Christianity (Orthodox)", "percentage": 20.0}, {"religion": "No Religion / Other", "percentage": 19.0}],
     "christianPercentage": 81.0, "evangelicalPercentage": 7.0, "unreachedPopulationPercentage": 3.0, "unreachedPeopleGroupsCount": 2, "securityLevel": "Low",
     "primaryLanguages": ["Latvian", "Russian"], "capitalCity": "Riga", "isIn1040Window": False, "activeMissionariesCount": 40, "activePrayerWarriorsCount": 920,
     "description": "Baltic nation with growing evangelical alliances and a rich heritage of Moravian revival. Churches actively serve society through family and youth ministries.",
     "prayerPoints": ["Revival across Latvian and Russian-speaking congregations", "Strengthening biblical families against depopulation and emigration", "Mobilizing Latvian youth to take the Gospel to post-Soviet nations"],
     "missionOpportunities": ["Family counseling and crisis pregnancy centers", "Youth camp and sports evangelism in Riga"]},

    {"id": "lie", "code": "LI", "code3": "LIE", "name": "Liechtenstein", "flag": "🇱🇮", "continent": "Europe", "population": 39000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 73.4}, {"religion": "Christianity (Protestant)", "percentage": 8.0}, {"religion": "Islam", "percentage": 6.0}, {"religion": "No Religion / Other", "percentage": 12.6}],
     "christianPercentage": 81.4, "evangelicalPercentage": 1.0, "unreachedPopulationPercentage": 3.0, "unreachedPeopleGroupsCount": 1, "securityLevel": "Low",
     "primaryLanguages": ["German", "Alemannic"], "capitalCity": "Vaduz", "isIn1040Window": False, "activeMissionariesCount": 3, "activePrayerWarriorsCount": 95,
     "description": "An alpine principality between Switzerland and Austria with an influential financial sector, needing deep evangelical discipleship.",
     "prayerPoints": ["Spiritual renewal in the Rhine Valley", "Financial integrity and generous kingdom philanthropy among business leaders", "Growth of local evangelical fellowships in Vaduz and Schaan"],
     "missionOpportunities": ["Marketplace ministry and business ethics seminars", "Youth discipleship"]},

    {"id": "ltu", "code": "LT", "code3": "LTU", "name": "Lithuania", "flag": "🇱🇹", "continent": "Europe", "population": 2860000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 74.0}, {"religion": "No Religion / Secular", "percentage": 17.0}, {"religion": "Christianity (Orthodox)", "percentage": 4.0}, {"religion": "Christianity (Evangelical/Protestant)", "percentage": 2.0}, {"religion": "Other", "percentage": 3.0}],
     "christianPercentage": 80.0, "evangelicalPercentage": 1.4, "unreachedPopulationPercentage": 4.0, "unreachedPeopleGroupsCount": 2, "securityLevel": "Low",
     "primaryLanguages": ["Lithuanian", "Russian", "Polish"], "capitalCity": "Vilnius", "isIn1040Window": False, "activeMissionariesCount": 38, "activePrayerWarriorsCount": 860,
     "description": "Known as the land of crosses (Hill of Crosses). Evangelical churches are multiplying in Vilnius and Kaunas, reaching the younger generation.",
     "prayerPoints": ["Spiritual rebirth from cultural Catholicism to personal relationship with Jesus", "Youth deliverance from depression and suicide", "Church planting across rural regional centers"],
     "missionOpportunities": ["University campus ministry in Vilnius and Kaunas", "Rehabilitation and addiction recovery centers"]},

    {"id": "lux", "code": "LU", "code3": "LUX", "name": "Luxembourg", "flag": "🇱🇺", "continent": "Europe", "population": 660000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 67.0}, {"religion": "No Religion / Secular", "percentage": 24.0}, {"religion": "Islam", "percentage": 3.0}, {"religion": "Christianity (Evangelical/Protestant)", "percentage": 3.0}, {"religion": "Other", "percentage": 3.0}],
     "christianPercentage": 70.0, "evangelicalPercentage": 1.5, "unreachedPopulationPercentage": 6.0, "unreachedPeopleGroupsCount": 3, "securityLevel": "Low",
     "primaryLanguages": ["Luxembourgish", "French", "German", "Portuguese"], "capitalCity": "Luxembourg City", "isIn1040Window": False, "activeMissionariesCount": 15, "activePrayerWarriorsCount": 350,
     "description": "Multinational financial hub with over 45% foreign residents. Vibrant international and Portuguese-speaking evangelical churches are active.",
     "prayerPoints": ["Gospel breakthrough in the global banking and European institutional workforce", "Unity among multinational and indigenous Luxembourgish congregations", "Discipleship of international youth"],
     "missionOpportunities": ["Marketplace and EU civil service outreach", "Portuguese and Francophone diaspora church planting"]},

    {"id": "mlt", "code": "MT", "code3": "MLT", "name": "Malta", "flag": "🇲🇹", "continent": "Europe", "population": 530000,
     "dominantReligions": [{"religion": "Christianity (Catholic - Official)", "percentage": 88.0}, {"religion": "No Religion / Secular", "percentage": 7.0}, {"religion": "Islam / Other", "percentage": 5.0}],
     "christianPercentage": 89.0, "evangelicalPercentage": 1.5, "unreachedPopulationPercentage": 3.0, "unreachedPeopleGroupsCount": 2, "securityLevel": "Low",
     "primaryLanguages": ["Maltese (Semitic script)", "English"], "capitalCity": "Valletta", "isIn1040Window": False, "activeMissionariesCount": 18, "activePrayerWarriorsCount": 420,
     "description": "Where the Apostle Paul was shipwrecked in 60 AD (Acts 28). Malta possesses a unique Semitic language with European culture, strategically situated for North African outreach.",
     "prayerPoints": ["Fresh encounter with the Holy Spirit across Maltese Catholic parishes", "Mobilizing Maltese believers for missionary service in North Africa and the Arab world", "Fruitfulness for refugee hospitality ministries"],
     "missionOpportunities": ["North African Arabic missionary preparation base", "Maritime and tourist evangelism"]},

    {"id": "mda", "code": "MD", "code3": "MDA", "name": "Moldova", "flag": "🇲🇩", "continent": "Europe", "population": 2500000,
     "dominantReligions": [{"religion": "Christianity (Eastern Orthodox)", "percentage": 90.0}, {"religion": "Christianity (Baptist/Pentecostal/Evangelical)", "percentage": 4.0}, {"religion": "No Religion / Other", "percentage": 6.0}],
     "christianPercentage": 94.0, "evangelicalPercentage": 3.8, "unreachedPopulationPercentage": 2.0, "unreachedPeopleGroupsCount": 2, "securityLevel": "Medium",
     "primaryLanguages": ["Romanian (Moldovan)", "Russian", "Gagauz"], "capitalCity": "Chisinau", "isIn1040Window": False, "activeMissionariesCount": 65, "activePrayerWarriorsCount": 1450,
     "description": "One of Europe's poorest nations with one of its most missionary-minded evangelical churches. Moldovan evangelists serve across Central Asia and the Caucasus.",
     "prayerPoints": ["Support and comfort for children left behind by migrant parents", "Spiritual breakthrough among Muslim-background Gagauz people in the south", "Endurance for Moldovan cross-cultural missionaries serving abroad"],
     "missionOpportunities": ["Orphan care and rural day-care centers", "Gagauz Turkic church planting", "Missionary training institutes in Chisinau"]},

    {"id": "mco", "code": "MC", "code3": "MCO", "name": "Monaco", "flag": "🇲🇨", "continent": "Europe", "population": 39000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 82.0}, {"religion": "No Religion / Secular", "percentage": 13.0}, {"religion": "Christianity (Protestant/Other)", "percentage": 5.0}],
     "christianPercentage": 87.0, "evangelicalPercentage": 1.2, "unreachedPopulationPercentage": 5.0, "unreachedPeopleGroupsCount": 1, "securityLevel": "Low",
     "primaryLanguages": ["French", "Monégasque", "English", "Italian"], "capitalCity": "Monaco", "isIn1040Window": False, "activeMissionariesCount": 4, "activePrayerWarriorsCount": 110,
     "description": "Riviera principality where Trans World Radio (TWR) established historic shortwave broadcasting towers after WWII to beam the Gospel into closed nations.",
     "prayerPoints": ["Gospel awakening among affluent and influential residents of the Riviera", "Continued global impact of Christian broadcasting networks based in Monaco"],
     "missionOpportunities": ["High-net-worth Christian philanthropic initiatives", "International professional discipleship"]},

    {"id": "mne", "code": "ME", "code3": "MNE", "name": "Montenegro", "flag": "🇲🇪", "continent": "Europe", "population": 620000,
     "dominantReligions": [{"religion": "Christianity (Serbian Orthodox)", "percentage": 72.0}, {"religion": "Islam (Sunni)", "percentage": 19.1}, {"religion": "Christianity (Catholic)", "percentage": 3.4}, {"religion": "Other / Secular", "percentage": 5.5}],
     "christianPercentage": 75.5, "evangelicalPercentage": 0.2, "unreachedPopulationPercentage": 22.0, "unreachedPeopleGroupsCount": 3, "securityLevel": "Low",
     "primaryLanguages": ["Montenegrin", "Serbian", "Bosnian", "Albanian"], "capitalCity": "Podgorica", "isIn1040Window": False, "activeMissionariesCount": 12, "activePrayerWarriorsCount": 280,
     "description": "Dramatic Balkan coastal and mountain nation with fewer than 300 known evangelical believers, presenting a frontier European church planting field.",
     "prayerPoints": ["Pioneer church planting in Podgorica, Nikšić, and coastal towns", "Gospel breakthrough among the Muslim Albanian and Bosniak populations in the south and east", "Raising up indigenous Montenegrin Christian leaders"],
     "missionOpportunities": ["Pioneer church planting teams", "Youth sports and adventure camp ministry"]},

    {"id": "nld", "code": "NL", "code3": "NLD", "name": "Netherlands", "flag": "🇳🇱", "continent": "Europe", "population": 17800000,
     "dominantReligions": [{"religion": "No Religion / Secular", "percentage": 55.0}, {"religion": "Christianity (Catholic)", "percentage": 19.8}, {"religion": "Christianity (Protestant/PKN)", "percentage": 14.4}, {"religion": "Islam (Moroccan/Turkish)", "percentage": 5.2}, {"religion": "Christianity (Evangelical/Pentecostal)", "percentage": 3.0}, {"religion": "Other", "percentage": 2.6}],
     "christianPercentage": 37.2, "evangelicalPercentage": 4.5, "unreachedPopulationPercentage": 8.0, "unreachedPeopleGroupsCount": 14, "securityLevel": "Low",
     "primaryLanguages": ["Dutch", "English", "Frisian", "Arabic"], "capitalCity": "Amsterdam", "isIn1040Window": False, "activeMissionariesCount": 280, "activePrayerWarriorsCount": 6200,
     "description": "Historic center of Reformed theology and mission (Youth With A Mission Amsterdam, Corrie ten Boom). Active prayer movements and immigrant churches are growing.",
     "prayerPoints": ["Spiritual rebirth across Dutch cities and university campuses", "Evangelism and discipleship among Moroccan and Turkish communities in Rotterdam and Amsterdam", "Revitalizing historic churches through prayer and mission"],
     "missionOpportunities": ["Red Light District outreach and anti-trafficking in Amsterdam", "Diaspora Muslim cafe ministries", "Cross-cultural missionary training in Heerde and Amsterdam"]},

    {"id": "mkd", "code": "MK", "code3": "MKD", "name": "North Macedonia", "flag": "🇲🇰", "continent": "Europe", "population": 1830000,
     "dominantReligions": [{"religion": "Christianity (Macedonian Orthodox)", "percentage": 64.8}, {"religion": "Islam (Sunni - Albanian/Turk/Roma)", "percentage": 33.3}, {"religion": "Other", "percentage": 1.9}],
     "christianPercentage": 65.0, "evangelicalPercentage": 0.3, "unreachedPopulationPercentage": 35.0, "unreachedPeopleGroupsCount": 5, "securityLevel": "Low",
     "primaryLanguages": ["Macedonian", "Albanian", "Turkish", "Romani"], "capitalCity": "Skopje", "isIn1040Window": False, "activeMissionariesCount": 24, "activePrayerWarriorsCount": 580,
     "description": "Where the 'Macedonian Call' came to the Apostle Paul (Acts 16:9). Today, small but zealous evangelical fellowships minister across ethnic divides.",
     "prayerPoints": ["Breakthrough among the 500,000 Muslim Albanians and Turks in western Macedonia", "Reconciliation and unity across Macedonian and Albanian believers", "Equipping young church planters in Skopje and Bitola"],
     "missionOpportunities": ["Roma and Albanian community development and literacy", "University campus ministry in Skopje"]},

    {"id": "nor", "code": "NO", "code3": "NOR", "name": "Norway", "flag": "🇳🇴", "continent": "Europe", "population": 5480000,
     "dominantReligions": [{"religion": "Christianity (Lutheran)", "percentage": 67.5}, {"religion": "No Religion / Secular", "percentage": 25.0}, {"religion": "Islam", "percentage": 3.5}, {"religion": "Christianity (Free Churches / Catholic)", "percentage": 4.0}],
     "christianPercentage": 71.5, "evangelicalPercentage": 8.5, "unreachedPopulationPercentage": 4.0, "unreachedPeopleGroupsCount": 4, "securityLevel": "Low",
     "primaryLanguages": ["Norwegian", "Sámi", "English"], "capitalCity": "Oslo", "isIn1040Window": False, "activeMissionariesCount": 160, "activePrayerWarriorsCount": 3800,
     "description": "Historically sent more missionaries per capita than almost any nation (Hans Nielsen Hauge revival). Today vibrant prayer movements contend for spiritual awakening.",
     "prayerPoints": ["A fresh Haugean spiritual awakening sweeping Norwegian youth and families", "Boldness against aggressive secularism and preservation of biblical values", "Continued sending of Norwegian missionaries to closed nations"],
     "missionOpportunities": ["Urban church planting in multi-cultural Oslo", "Frontier mission training and prayer centers in Bergen and Kristiansand"]},

    {"id": "pol", "code": "PL", "code3": "POL", "name": "Poland", "flag": "🇵🇱", "continent": "Europe", "population": 37700000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 84.8}, {"religion": "No Religion / Secular", "percentage": 12.0}, {"religion": "Christianity (Orthodox)", "percentage": 1.3}, {"religion": "Christianity (Evangelical/Protestant)", "percentage": 0.5}, {"religion": "Other", "percentage": 1.4}],
     "christianPercentage": 86.6, "evangelicalPercentage": 0.4, "unreachedPopulationPercentage": 2.0, "unreachedPeopleGroupsCount": 3, "securityLevel": "Low",
     "primaryLanguages": ["Polish", "Ukrainian", "Silesian"], "capitalCity": "Warsaw", "isIn1040Window": False, "activeMissionariesCount": 140, "activePrayerWarriorsCount": 3400,
     "description": "Deeply religious nation that hosted millions of Ukrainian refugees with Christian generosity. Evangelical church planting is accelerating in major academic hubs.",
     "prayerPoints": ["Transforming nominal tradition into living, personal faith in Jesus Christ", "Rapid church planting in hundreds of Polish towns without a single evangelical church", "Blessing and discipleship for the large Ukrainian refugee population"],
     "missionOpportunities": ["University campus ministry in Warsaw, Krakow, and Wroclaw", "Ukrainian refugee family care and integration", "Christian publishing and digital media in Polish"]},

    {"id": "prt", "code": "PT", "code3": "PRT", "name": "Portugal", "flag": "🇵🇹", "continent": "Europe", "population": 10300000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 80.2}, {"religion": "No Religion / Secular", "percentage": 14.1}, {"religion": "Christianity (Evangelical/Protestant)", "percentage": 3.0}, {"religion": "Other", "percentage": 2.7}],
     "christianPercentage": 83.2, "evangelicalPercentage": 2.2, "unreachedPopulationPercentage": 3.0, "unreachedPeopleGroupsCount": 3, "securityLevel": "Low",
     "primaryLanguages": ["Portuguese"], "capitalCity": "Lisbon", "isIn1040Window": False, "activeMissionariesCount": 85, "activePrayerWarriorsCount": 2200,
     "description": "Historic global maritime explorer nation. Today, Brazilian and African immigrant churches are revitalizing Portuguese evangelical life with passion.",
     "prayerPoints": ["Spiritual revival across the historic towns of the interior", "Fruitful partnership between indigenous Portuguese and Brazilian immigrant churches", "Sending Portuguese-speaking workers to Mozambique, Angola, and Guinea-Bissau"],
     "missionOpportunities": ["Church planting in interior regions (Alentejo and Trás-os-Montes)", "University student ministry in Coimbra and Lisbon"]},

    {"id": "rou", "code": "RO", "code3": "ROU", "name": "Romania", "flag": "🇷🇴", "continent": "Europe", "population": 19000000,
     "dominantReligions": [{"religion": "Christianity (Romanian Orthodox)", "percentage": 85.3}, {"religion": "Christianity (Evangelical/Baptist/Pentecostal)", "percentage": 6.2}, {"religion": "Christianity (Catholic)", "percentage": 4.5}, {"religion": "No Religion / Other", "percentage": 4.0}],
     "christianPercentage": 96.0, "evangelicalPercentage": 5.4, "unreachedPopulationPercentage": 2.5, "unreachedPeopleGroupsCount": 4, "securityLevel": "Low",
     "primaryLanguages": ["Romanian", "Hungarian", "Romani"], "capitalCity": "Bucharest", "isIn1040Window": False, "activeMissionariesCount": 240, "activePrayerWarriorsCount": 5800,
     "description": "A spiritual powerhouse in Eastern Europe (Richard Wurmbrand). Romanian evangelicals are among the most active missionary senders to Central Asia and the Balkans.",
     "prayerPoints": ["Mobilizing thousands of Romanian youth for cross-cultural missions in the 10/40 window", "Spiritual breakthrough in impoverished rural villages and Roma communities", "Unity and holiness across Romanian evangelical denominations"],
     "missionOpportunities": ["Missionary training and sending agencies in Timișoara, Cluj, and Oradea", "Roma community development and church planting", "Orphan care and social outreach"]},

    {"id": "rus", "code": "RU", "code3": "RUS", "name": "Russia", "flag": "🇷🇺", "continent": "Europe", "population": 143400000,
     "dominantReligions": [{"religion": "Christianity (Russian Orthodox)", "percentage": 68.0}, {"religion": "No Religion / Atheist", "percentage": 18.0}, {"religion": "Islam (Tatar, North Caucasus)", "percentage": 10.0}, {"religion": "Christianity (Evangelical/Baptist/Pentecostal)", "percentage": 1.5}, {"religion": "Buddhism / Shamanism", "percentage": 2.5}],
     "christianPercentage": 69.5, "evangelicalPercentage": 1.5, "unreachedPopulationPercentage": 14.0, "unreachedPeopleGroupsCount": 112, "securityLevel": "Extreme",
     "primaryLanguages": ["Russian", "Tatar", "Chechen", "Chuvash", "Bashkir", "Avar"], "capitalCity": "Moscow", "isIn1040Window": True, "activeMissionariesCount": 380, "activePrayerWarriorsCount": 9200,
     "description": "Stretches across 11 time zones. Contains over 100 unreached ethnic groups in the North Caucasus (Chechens, Dagestanis, Circassians) and Siberia.",
     "prayerPoints": ["Peace, justice, and cessation of warfare and military aggression", "Supernatural breakthrough among 100+ unreached Muslim peoples in the North Caucasus and Volga", "Perseverance and boldness for underground and registered evangelical churches"],
     "missionOpportunities": ["Siberian indigenous tribal church planting", "North Caucasus digital scripture and audio Bible distribution", "Rehabilitation ministries and orphan support"]},

    {"id": "smr", "code": "SM", "code3": "SMR", "name": "San Marino", "flag": "🇸🇲", "continent": "Europe", "population": 34000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 91.0}, {"religion": "Secular / Other", "percentage": 9.0}],
     "christianPercentage": 91.0, "evangelicalPercentage": 0.3, "unreachedPopulationPercentage": 4.0, "unreachedPeopleGroupsCount": 1, "securityLevel": "Low",
     "primaryLanguages": ["Italian"], "capitalCity": "City of San Marino", "isIn1040Window": False, "activeMissionariesCount": 2, "activePrayerWarriorsCount": 85,
     "description": "The world's oldest surviving sovereign republic, founded by Saint Marinus in 301 AD. In need of living evangelical witness and discipleship.",
     "prayerPoints": ["Spiritual rebirth from religious heritage into dynamic personal faith in Christ", "Establishment of a thriving indigenous evangelical congregation"],
     "missionOpportunities": ["Youth ministry and home Bible studies"]},

    {"id": "srb", "code": "RS", "code3": "SRB", "name": "Serbia", "flag": "🇷🇸", "continent": "Europe", "population": 6600000,
     "dominantReligions": [{"religion": "Christianity (Serbian Orthodox)", "percentage": 84.6}, {"religion": "Christianity (Catholic)", "percentage": 5.0}, {"religion": "Islam (Bosniak/Roma)", "percentage": 3.1}, {"religion": "Christianity (Protestant/Evangelical)", "percentage": 1.0}, {"religion": "Other", "percentage": 6.3}],
     "christianPercentage": 90.6, "evangelicalPercentage": 0.8, "unreachedPopulationPercentage": 5.0, "unreachedPeopleGroupsCount": 4, "securityLevel": "Low",
     "primaryLanguages": ["Serbian", "Hungarian", "Bosnian", "Romani"], "capitalCity": "Belgrade", "isIn1040Window": False, "activeMissionariesCount": 45, "activePrayerWarriorsCount": 980,
     "description": "Crossroad of the Balkans. Evangelical churches are growing in Vojvodina and Belgrade, active in humanitarian and Roma reconciliation.",
     "prayerPoints": ["Deep healing from historical Balkan conflicts through the Cross", "Fruitful church planting among Roma and Muslim Sandžak Bosniaks", "Spiritual awakening among university students in Belgrade and Novi Sad"],
     "missionOpportunities": ["Roma education and church planting in southern Serbia", "University campus ministry in Belgrade"]},

    {"id": "svk", "code": "SK", "code3": "SVK", "name": "Slovakia", "flag": "🇸🇰", "continent": "Europe", "population": 5400000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 56.0}, {"religion": "No Religion / Secular", "percentage": 24.0}, {"religion": "Christianity (Lutheran)", "percentage": 5.3}, {"religion": "Christianity (Greek Catholic)", "percentage": 4.0}, {"religion": "Christianity (Evangelical)", "percentage": 1.8}, {"religion": "Other", "percentage": 8.9}],
     "christianPercentage": 67.1, "evangelicalPercentage": 1.8, "unreachedPopulationPercentage": 3.0, "unreachedPeopleGroupsCount": 2, "securityLevel": "Low",
     "primaryLanguages": ["Slovak", "Hungarian", "Romani"], "capitalCity": "Bratislava", "isIn1040Window": False, "activeMissionariesCount": 48, "activePrayerWarriorsCount": 1100,
     "description": "Witnessing exciting charismatic renewals and prayer movements (Godzone) mobilizing thousands of Catholic and evangelical youth.",
     "prayerPoints": ["Continued momentum of youth revival movements across Slovakia", "Rapid multiplication of churches in marginalized Roma settlements in the east", "Sending Slovak missionaries to Ukraine, the Balkans, and Asia"],
     "missionOpportunities": ["Eastern Slovakian Roma community centers and churches", "Youth worship and creative arts training"]},

    {"id": "svn", "code": "SI", "code3": "SVN", "name": "Slovenia", "flag": "🇸🇮", "continent": "Europe", "population": 2100000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 57.8}, {"religion": "No Religion / Secular", "percentage": 30.0}, {"religion": "Islam", "percentage": 2.8}, {"religion": "Christianity (Orthodox / Evangelical)", "percentage": 2.5}, {"religion": "Other", "percentage": 6.9}],
     "christianPercentage": 60.3, "evangelicalPercentage": 0.2, "unreachedPopulationPercentage": 4.0, "unreachedPeopleGroupsCount": 2, "securityLevel": "Low",
     "primaryLanguages": ["Slovene"], "capitalCity": "Ljubljana", "isIn1040Window": False, "activeMissionariesCount": 22, "activePrayerWarriorsCount": 480,
     "description": "Primož Trubar gave Slovenes their first printed book (the Bible). Today, fewer than 2,000 evangelical Christians exist in this beautiful nation.",
     "prayerPoints": ["Re-awakening the Protestant Reformation legacy of Primož Trubar", "Planting vibrant evangelical churches in every major municipality", "Deliverance of youth from materialism and secularism"],
     "missionOpportunities": ["Pioneer church planting in Ljubljana, Maribor, and Celje", "Outdoor adventure and youth camp ministry"]},

    {"id": "esp", "code": "ES", "code3": "ESP", "name": "Spain", "flag": "🇪🇸", "continent": "Europe", "population": 48000000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 58.0}, {"religion": "No Religion / Secular", "percentage": 37.0}, {"religion": "Islam (Moroccan/Pakistani)", "percentage": 2.5}, {"religion": "Christianity (Evangelical/Gypsy/Latino)", "percentage": 2.0}, {"religion": "Other", "percentage": 0.5}],
     "christianPercentage": 60.0, "evangelicalPercentage": 1.5, "unreachedPopulationPercentage": 6.0, "unreachedPeopleGroupsCount": 18, "securityLevel": "Low",
     "primaryLanguages": ["Spanish (Castilian)", "Catalan", "Galician", "Basque", "Arabic"], "capitalCity": "Madrid", "isIn1040Window": False, "activeMissionariesCount": 290, "activePrayerWarriorsCount": 6100,
     "description": "Historic land of the Camino de Santiago. Immigrant Latin American and Gitano (Gypsy) churches are driving evangelical growth, though thousands of villages lack a church.",
     "prayerPoints": ["Church planting across over 8,000 Spanish towns without an evangelical witness ('Pueblos de España')", "Spiritual breakthrough among Moroccan and North African immigrants in Andalucia and Catalonia", "Revival in Spanish universities in Madrid, Barcelona, and Salamanca"],
     "missionOpportunities": ["Pioneer church planting in rural unreached municipalities", "North African diaspora ministry in Almería and Ceuta/Melilla", "Camino de Santiago pilgrim hospitality and evangelism"]},

    {"id": "swe", "code": "SE", "code3": "SWE", "name": "Sweden", "flag": "🇸🇪", "continent": "Europe", "population": 10500000,
     "dominantReligions": [{"religion": "Christianity (Lutheran)", "percentage": 53.6}, {"religion": "No Religion / Secular", "percentage": 38.0}, {"religion": "Islam", "percentage": 5.0}, {"religion": "Christianity (Free Churches / Catholic / Orthodox)", "percentage": 3.4}],
     "christianPercentage": 57.0, "evangelicalPercentage": 6.5, "unreachedPopulationPercentage": 6.5, "unreachedPeopleGroupsCount": 8, "securityLevel": "Low",
     "primaryLanguages": ["Swedish", "Arabic", "Sámi", "English"], "capitalCity": "Stockholm", "isIn1040Window": False, "activeMissionariesCount": 180, "activePrayerWarriorsCount": 4200,
     "description": "Famous for the historic Pentecostal revival (Lewi Pethrus) and mission sending. Today immigrant churches in Stockholm and Malmö are leading outreach.",
     "prayerPoints": ["Spiritual rebirth in secular Swedish society", "Evangelism and integration in immigrant suburbs (Rinkeby, Rosengård)", "Rekindling the missionary sending passion of Swedish youth"],
     "missionOpportunities": ["Immigrant diaspora church planting and youth mentorship", "Christian media and digital discipleship in Stockholm"]},

    {"id": "che", "code": "CH", "code3": "CHE", "name": "Switzerland", "flag": "🇨🇭", "continent": "Europe", "population": 8800000,
     "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 33.8}, {"religion": "Christianity (Reformed/Protestant)", "percentage": 21.8}, {"religion": "No Religion / Secular", "percentage": 34.0}, {"religion": "Islam", "percentage": 5.4}, {"religion": "Christianity (Evangelical/Free)", "percentage": 3.0}, {"religion": "Other", "percentage": 2.0}],
     "christianPercentage": 58.6, "evangelicalPercentage": 4.2, "unreachedPopulationPercentage": 6.0, "unreachedPeopleGroupsCount": 6, "securityLevel": "Low",
     "primaryLanguages": ["German", "French", "Italian", "Romansh"], "capitalCity": "Bern", "isIn1040Window": False, "activeMissionariesCount": 210, "activePrayerWarriorsCount": 4600,
     "description": "Cradle of the Calvin and Zwingli Reformations and the Anabaptist movement. Strong mission training bases and prayer houses operate across the Alps.",
     "prayerPoints": ["Spiritual renewal in the historic cantons of Geneva, Zurich, and Bern", "Generous financial mobilization for global unreached missions", "Effective youth evangelism against secular materialism"],
     "missionOpportunities": ["International diplomatic and UN worker ministry in Geneva", "Alpine prayer retreat centers and missionary care"]},

    {"id": "ukr", "code": "UA", "code3": "UKR", "name": "Ukraine", "flag": "🇺🇦", "continent": "Europe", "population": 38000000,
     "dominantReligions": [{"religion": "Christianity (Ukrainian Orthodox)", "percentage": 72.0}, {"religion": "Christianity (Greek Catholic)", "percentage": 9.0}, {"religion": "Christianity (Evangelical/Baptist/Pentecostal)", "percentage": 3.5}, {"religion": "No Religion / Other", "percentage": 15.5}],
     "christianPercentage": 84.5, "evangelicalPercentage": 3.5, "unreachedPopulationPercentage": 2.5, "unreachedPeopleGroupsCount": 6, "securityLevel": "Extreme",
     "primaryLanguages": ["Ukrainian", "Russian", "Crimean Tatar"], "capitalCity": "Kyiv", "isIn1040Window": False, "activeMissionariesCount": 380, "activePrayerWarriorsCount": 9800,
     "description": "Historically known as the 'Bible Belt of the Soviet Union.' Despite devastating war, Ukrainian churches have become heroic relief distribution centers.",
     "prayerPoints": ["Immediate end to the war, protection of civilians, and restoration of righteous peace", "Sustained strength and trauma healing for millions of displaced families and orphans", "Spiritual breakthrough among Crimean Tatars and unreached ethnic groups"],
     "missionOpportunities": ["Frontline humanitarian food and medical relief", "Trauma healing counseling and rehabilitation centers in Kyiv, Lviv, and Kharkiv", "Rebuilding destroyed church community centers"]},

    {"id": "gbr", "code": "GB", "code3": "GBR", "name": "United Kingdom", "flag": "🇬🇧", "continent": "Europe", "population": 67700000,
     "dominantReligions": [{"religion": "Christianity (Anglican/Catholic/Protestant)", "percentage": 46.2}, {"religion": "No Religion / Secular", "percentage": 37.2}, {"religion": "Islam", "percentage": 6.5}, {"religion": "Hinduism / Sikhism / Other", "percentage": 5.1}, {"religion": "Christianity (Evangelical/Pentecostal/Black Majority)", "percentage": 5.0}],
     "christianPercentage": 51.2, "evangelicalPercentage": 8.0, "unreachedPopulationPercentage": 10.0, "unreachedPeopleGroupsCount": 38, "securityLevel": "Low",
     "primaryLanguages": ["English", "Welsh", "Scots Gaelic", "Urdu", "Punjabi", "Polish", "Bengali"], "capitalCity": "London", "isIn1040Window": False, "activeMissionariesCount": 680, "activePrayerWarriorsCount": 12500,
     "description": "The nation of George Whitefield, John Wesley, Charles Spurgeon, and William Carey. Vibrant diaspora (African, Caribbean, Asian) churches in London, Birmingham, and Manchester are driving revival.",
     "prayerPoints": ["National revival in historic British churches to turn back aggressive secularism", "Spiritual awakening in London's multi-ethnic unreached communities (Bengali Sylhetis, Mirpuri Pakistanis, Somalis)", "Mobilizing a new generation of British youth for cross-cultural missions"],
     "missionOpportunities": ["South Asian diaspora church planting in East London, Bradford, and Birmingham", "University student discipleship in Oxford, Cambridge, and London", "Inner-city youth violence intervention ministries"]}
]

print(f"Europe countries: {len(EUROPE_COUNTRIES)}")
