import json

# Comprehensive database of all 195 Sovereign Countries with full missional profiles
countries = [
    # --- ASIA & MIDDLE EAST (48) ---
    {
        "id": "afg", "code": "AF", "code3": "AFG", "name": "Afghanistan", "flag": "🇦🇫", "continent": "Asia",
        "population": 41130000,
        "dominantReligions": [{"religion": "Islam (Sunni)", "percentage": 89.7}, {"religion": "Islam (Shia)", "percentage": 10.0}, {"religion": "Christianity", "percentage": 0.05}, {"religion": "Other", "percentage": 0.25}],
        "christianPercentage": 0.05, "evangelicalPercentage": 0.03, "unreachedPopulationPercentage": 99.8, "unreachedPeopleGroupsCount": 72,
        "securityLevel": "Extreme", "primaryLanguages": ["Dari", "Pashto", "Uzbek", "Turkmen"], "capitalCity": "Kabul", "isIn1040Window": True,
        "activeMissionariesCount": 14, "activePrayerWarriorsCount": 1840,
        "description": "A landlocked country at the crossroads of Central and South Asia. One of the least reached nations on Earth where underground networks persist under intense pressure.",
        "prayerPoints": ["Protection and boldness for underground house church believers", "Dreams and visions revealing Jesus the Prince of Peace across tribal elders", "Radio and digital scripture broadcasts in remote valleys"],
        "missionOpportunities": ["Digital & satellite broadcasting in Pashto and Dari", "Refugee diaspora outreach in neighboring nations"]
    },
    {
        "id": "arm", "code": "AM", "code3": "ARM", "name": "Armenia", "flag": "🇦🇲", "continent": "Asia",
        "population": 2780000,
        "dominantReligions": [{"religion": "Christianity (Armenian Apostolic)", "percentage": 92.5}, {"religion": "Christianity (Evangelical/Catholic)", "percentage": 4.5}, {"religion": "Yazidi / Other", "percentage": 3.0}],
        "christianPercentage": 97.0, "evangelicalPercentage": 2.8, "unreachedPopulationPercentage": 3.5, "unreachedPeopleGroupsCount": 2,
        "securityLevel": "Medium", "primaryLanguages": ["Armenian", "Russian"], "capitalCity": "Yerevan", "isIn1040Window": False,
        "activeMissionariesCount": 38, "activePrayerWarriorsCount": 1100,
        "description": "The first nation to adopt Christianity as state religion in 301 AD. Youth are experiencing spiritual renewal and reaching neighboring Caucasus peoples.",
        "prayerPoints": ["Peace and security along border regions", "Fresh evangelical revival in historic Apostolic communities", "Outreach to neighboring unreached Muslim Caucasus peoples"],
        "missionOpportunities": ["Yazidi refugee ministry", "Christian tech entrepreneurship"]
    },
    {
        "id": "aze", "code": "AZ", "code3": "AZE", "name": "Azerbaijan", "flag": "🇦🇿", "continent": "Asia",
        "population": 10400000,
        "dominantReligions": [{"religion": "Islam (Shia 65% / Sunni 35%)", "percentage": 96.0}, {"religion": "Christianity (Orthodox)", "percentage": 3.0}, {"religion": "Other", "percentage": 1.0}],
        "christianPercentage": 3.0, "evangelicalPercentage": 0.2, "unreachedPopulationPercentage": 97.0, "unreachedPeopleGroupsCount": 18,
        "securityLevel": "High", "primaryLanguages": ["Azerbaijani (Azeri)", "Russian", "Lezgi"], "capitalCity": "Baku", "isIn1040Window": True,
        "activeMissionariesCount": 22, "activePrayerWarriorsCount": 920,
        "description": "A secular post-Soviet Muslim republic where vibrant indigenous Azeri evangelical house churches have emerged over the last three decades.",
        "prayerPoints": ["Registration freedom for Protestant churches", "Breakthrough among Lezgin, Talysh, and Mountain Jewish communities", "Courage for young converts facing family pressure"],
        "missionOpportunities": ["Digital media discipleship in Azeri", "Business as mission in Baku"]
    },
    {
        "id": "bhr", "code": "BH", "code3": "BHR", "name": "Bahrain", "flag": "🇧🇭", "continent": "Middle East",
        "population": 1540000,
        "dominantReligions": [{"religion": "Islam", "percentage": 70.3}, {"religion": "Christianity (Expatriate)", "percentage": 14.5}, {"religion": "Hinduism", "percentage": 9.8}, {"religion": "Other", "percentage": 5.4}],
        "christianPercentage": 14.5, "evangelicalPercentage": 2.5, "unreachedPopulationPercentage": 74.0, "unreachedPeopleGroupsCount": 10,
        "securityLevel": "Medium", "primaryLanguages": ["Arabic", "English", "Urdu"], "capitalCity": "Manama", "isIn1040Window": True,
        "activeMissionariesCount": 20, "activePrayerWarriorsCount": 880,
        "description": "An open Gulf kingdom where expatriate churches worship freely. Home of the historic American Mission Hospital founded in 1902.",
        "prayerPoints": ["Salvation among indigenous Bahraini Arab families", "Unity across diverse expatriate churches", "Fruitfulness for Christian medical services"],
        "missionOpportunities": ["Migrant worker care and evangelism", "Arabic digital media outreach"]
    },
    {
        "id": "bgd", "code": "BD", "code3": "BGD", "name": "Bangladesh", "flag": "🇧🇩", "continent": "Asia",
        "population": 171200000,
        "dominantReligions": [{"religion": "Islam (Sunni)", "percentage": 89.1}, {"religion": "Hinduism", "percentage": 10.0}, {"religion": "Christianity", "percentage": 0.5}, {"religion": "Buddhism", "percentage": 0.4}],
        "christianPercentage": 0.5, "evangelicalPercentage": 0.4, "unreachedPopulationPercentage": 98.8, "unreachedPeopleGroupsCount": 298,
        "securityLevel": "High", "primaryLanguages": ["Bengali (Bangla)", "Sylheti", "Chittagonian"], "capitalCity": "Dhaka", "isIn1040Window": True,
        "activeMissionariesCount": 185, "activePrayerWarriorsCount": 4200,
        "description": "Densely populated 10/40 window nation where disciple-making movements (Isa Jamaat) are multiplying rapidly across rural districts.",
        "prayerPoints": ["Rapid multiplication of disciples among 150M+ Bengali Muslims", "Hope and healing for 1M+ Rohingya refugees in Cox's Bazar", "Protection for rural believers facing social boycotts"],
        "missionOpportunities": ["Microfinance and community development", "Rohingya refugee healthcare"]
    },
    {
        "id": "btn", "code": "BT", "code3": "BTN", "name": "Bhutan", "flag": "🇧🇹", "continent": "Asia",
        "population": 787000,
        "dominantReligions": [{"religion": "Buddhism (Vajrayana)", "percentage": 74.8}, {"religion": "Hinduism", "percentage": 22.6}, {"religion": "Christianity", "percentage": 2.6}],
        "christianPercentage": 2.6, "evangelicalPercentage": 2.0, "unreachedPopulationPercentage": 92.0, "unreachedPeopleGroupsCount": 21,
        "securityLevel": "High", "primaryLanguages": ["Dzongkha", "Nepali", "Tshangla"], "capitalCity": "Thimphu", "isIn1040Window": True,
        "activeMissionariesCount": 8, "activePrayerWarriorsCount": 780,
        "description": "The Himalayan Kingdom of the Thunder Dragon. Indigenous Drukpa and Nepali believers quietly multiply house churches across valleys.",
        "prayerPoints": ["Legal recognition for church fellowships", "Awakening among the Drukpa Buddhist majority", "Strength for underground house church leaders"],
        "missionOpportunities": ["Dzongkha audio Bible translation", "Vocational skill training"]
    },
    {
        "id": "brn", "code": "BN", "code3": "BRN", "name": "Brunei", "flag": "🇧🇳", continent: "Asia",
        "population": 450000,
        "dominantReligions": [{"religion": "Islam (Sunni - Official)", "percentage": 82.1}, {"religion": "Christianity", "percentage": 8.7}, {"religion": "Buddhism", "percentage": 7.8}, {"religion": "Other", "percentage": 1.4}],
        "christianPercentage": 8.7, "evangelicalPercentage": 1.2, "unreachedPopulationPercentage": 85.0, "unreachedPeopleGroupsCount": 6,
        "securityLevel": "High", "primaryLanguages": ["Malay", "English", "Chinese"], "capitalCity": "Bandar Seri Begawan", "isIn1040Window": True,
        "activeMissionariesCount": 6, "activePrayerWarriorsCount": 450,
        "description": "Oil-rich Sultanate on Borneo governed by Sharia penal code. Expatriate and indigenous Chinese/Dusun Christians maintain faithful prayer.",
        "prayerPoints": ["Gospel access among Malay majority", "Courage for local believers under strict religious laws", "Revival among Christian youth"],
        "missionOpportunities": ["Professional expat workplace ministry", "Digital discipleship"]
    },
    {
        "id": "khm", "code": "KH", "code3": "KHM", "name": "Cambodia", "flag": "🇰🇭", "continent": "Asia",
        "population": 16940000,
        "dominantReligions": [{"religion": "Buddhism (Theravada)", "percentage": 97.1}, {"religion": "Islam (Cham)", "percentage": 2.0}, {"religion": "Christianity", "percentage": 0.8}, {"religion": "Other", "percentage": 0.1}],
        "christianPercentage": 0.8, "evangelicalPercentage": 0.6, "unreachedPopulationPercentage": 97.5, "unreachedPeopleGroupsCount": 26,
        "securityLevel": "Low", "primaryLanguages": ["Khmer", "Cham"], "capitalCity": "Phnom Penh", "isIn1040Window": True,
        "activeMissionariesCount": 160, "activePrayerWarriorsCount": 2600,
        "description": "Rising from the tragedy of the Khmer Rouge. Today churches are planted in hundreds of rural villages and among the Muslim Cham minority.",
        "prayerPoints": ["Church planting movements in all 14,000 rural villages", "Gospel breakthrough among 350,000 Muslim Cham people", "Discipleship to heal generational trauma"],
        "missionOpportunities": ["Anti-trafficking and orphan care", "Village clean water and church planting"]
    },
    {
        "id": "chn", "code": "CN", "code3": "CHN", "name": "China", "flag": "🇨🇳", "continent": "Asia",
        "population": 1412000000,
        "dominantReligions": [{"religion": "Non-religious / Atheist", "percentage": 52.2}, {"religion": "Buddhism / Folk Religions", "percentage": 30.0}, {"religion": "Christianity (House & TSPM)", "percentage": 8.5}, {"religion": "Islam (Hui / Uyghur)", "percentage": 1.8}, {"religion": "Other", "percentage": 7.5}],
        "christianPercentage": 8.5, "evangelicalPercentage": 5.8, "unreachedPopulationPercentage": 85.0, "unreachedPeopleGroupsCount": 445,
        "securityLevel": "Extreme", "primaryLanguages": ["Mandarin (Putonghua)", "Cantonese", "Wu", "Tibetan", "Uyghur"], "capitalCity": "Beijing", "isIn1040Window": True,
        "activeMissionariesCount": 950, "activePrayerWarriorsCount": 18500,
        "description": "Home to the world's largest underground house church movement (estimated 80-100 million believers). Actively mobilizing the 'Back to Jerusalem' vision.",
        "prayerPoints": ["Protection and perseverance for unregistered house church networks", "Supernatural gospel breakthrough among Tibetan Buddhists and Uyghur Muslims", "Sending thousands of Chinese missionaries across Central Asia"],
        "missionOpportunities": ["Tibetan and frontier minority Bible translation", "Digital and app-based discipleship"]
    },
    {
        "id": "cyp", "code": "CY", "code3": "CYP", "name": "Cyprus", "flag": "🇨🇾", "continent": "Europe",
        "population": 1250000,
        "dominantReligions": [{"religion": "Christianity (Greek Orthodox)", "percentage": 73.0}, {"religion": "Islam (Turkish Cypriot)", "percentage": 18.0}, {"religion": "Other", "percentage": 9.0}],
        "christianPercentage": 75.0, "evangelicalPercentage": 1.2, "unreachedPopulationPercentage": 19.0, "unreachedPeopleGroupsCount": 2,
        "securityLevel": "Low", "primaryLanguages": ["Greek", "Turkish", "English"], "capitalCity": "Nicosia", "isIn1040Window": False,
        "activeMissionariesCount": 55, "activePrayerWarriorsCount": 820,
        "description": "Visited by Paul and Barnabas (Acts 13). Today serves as a vital strategic media, radio, and training springboard into the Middle East.",
        "prayerPoints": ["Peace and reconciliation between Greek and Turkish communities", "Awakening among Turkish Cypriots in the north", "Fruitfulness for Middle East radio and digital ministries based in Cyprus"],
        "missionOpportunities": ["Middle East satellite and radio broadcast hubs", "University student ministry in Nicosia"]
    },
    {
        "id": "geo", "code": "GE", "code3": "GEO", "name": "Georgia", "flag": "🇬🇪", "continent": "Asia",
        "population": 3710000,
        "dominantReligions": [{"religion": "Christianity (Georgian Orthodox)", "percentage": 83.4}, {"religion": "Islam (Sunni/Shia)", "percentage": 10.7}, {"religion": "Christianity (Armenian Apostolic / Catholic)", "percentage": 3.9}, {"religion": "Other", "percentage": 2.0}],
        "christianPercentage": 87.3, "evangelicalPercentage": 1.5, "unreachedPopulationPercentage": 12.0, "unreachedPeopleGroupsCount": 7,
        "securityLevel": "Medium", "primaryLanguages": ["Georgian", "Azeri", "Armenian", "Russian"], "capitalCity": "Tbilisi", "isIn1040Window": False,
        "activeMissionariesCount": 35, "activePrayerWarriorsCount": 940,
        "description": "Ancient Christian nation in the Caucasus with rich liturgical history. Evangelical churches are growing among urban youth and reaching Muslim Adjarians and Azeris.",
        "prayerPoints": ["Revival of personal faith in Christ within the Orthodox community", "Gospel breakthrough among Muslim Kists, Avars, and Azeris in border regions", "Healing of past regional conflicts"],
        "missionOpportunities": ["Caucasus mountain village outreach", "Youth and student ministry in Tbilisi"]
    },
    {
        "id": "ind", "code": "IN", "code3": "IND", "name": "India", "flag": "🇮🇳", "continent": "Asia",
        "population": 1428000000,
        "dominantReligions": [{"religion": "Hinduism", "percentage": 79.8}, {"religion": "Islam", "percentage": 14.2}, {"religion": "Christianity", "percentage": 2.3}, {"religion": "Sikhism", "percentage": 1.7}, {"religion": "Buddhism / Jainism / Other", "percentage": 2.0}],
        "christianPercentage": 2.3, "evangelicalPercentage": 1.8, "unreachedPopulationPercentage": 95.0, "unreachedPeopleGroupsCount": 2180,
        "securityLevel": "Extreme", "primaryLanguages": ["Hindi", "English", "Bengali", "Telugu", "Marathi", "Tamil", "Urdu", "Gujarati"], "capitalCity": "New Delhi", "isIn1040Window": True,
        "activeMissionariesCount": 1250, "activePrayerWarriorsCount": 22000,
        "description": "The epicenter of the global unreached world, containing over 2,000 unreached castes and tribes. Church planting movements are exploding in northern Hindi belt.",
        "prayerPoints": ["Protection for rural pastors and house churches facing anti-conversion persecution", "Breakthrough across 2,000+ unreached Hindu castes (Brahmin to Dalit)", "Discipleship movements in the 600,000 villages of the Ganges River plains"],
        "missionOpportunities": ["Village church planter sponsorship", "Slum children education and women empowerment", "Mother-tongue audio Bible recording"]
    },
    {
        "id": "idn", "code": "ID", "code3": "IDN", "name": "Indonesia", "flag": "🇮🇩", "continent": "Asia",
        "population": 277500000,
        "dominantReligions": [{"religion": "Islam (Sunni)", "percentage": 86.7}, {"religion": "Christianity (Protestant)", "percentage": 7.6}, {"religion": "Christianity (Catholic)", "percentage": 3.1}, {"religion": "Hinduism (Bali)", "percentage": 1.7}, {"religion": "Other", "percentage": 0.9}],
        "christianPercentage": 10.7, "evangelicalPercentage": 3.2, "unreachedPopulationPercentage": 65.0, "unreachedPeopleGroupsCount": 225,
        "securityLevel": "Medium", "primaryLanguages": ["Indonesian (Bahasa)", "Javanese", "Sundanese", "Madurese", "Minangkabau"], "capitalCity": "Jakarta (Nusantara)", "isIn1040Window": True,
        "activeMissionariesCount": 450, "activePrayerWarriorsCount": 9200,
        "description": "World's largest Muslim-majority nation across 17,000 islands. Possesses strong prayer towers (Jejaring Doa Nasional) sending workers to unreached Sunda and Madura tribes.",
        "prayerPoints": ["Gospel breakthrough among the 40M unreached Sundanese and 15M Madurese", "Unity and protection for island churches against radical factions", "24/7 prayer movement expansion across all 38 provinces"],
        "missionOpportunities": ["Remote island medical boat evangelism", "Christian higher education and digital media", "Sundanese audio Bible distribution"]
    },
    {
        "id": "irn", "code": "IR", "code3": "IRN", "name": "Iran", "flag": "🇮🇷", "continent": "Middle East",
        "population": 88550000,
        "dominantReligions": [{"religion": "Islam (Twelver Shia - Official)", "percentage": 96.0}, {"religion": "Islam (Sunni)", "percentage": 3.0}, {"religion": "Christianity (Underground / Armenian)", "percentage": 0.8}, {"religion": "Other", "percentage": 0.2}],
        "christianPercentage": 0.8, "evangelicalPercentage": 0.7, "unreachedPopulationPercentage": 98.5, "unreachedPeopleGroupsCount": 88,
        "securityLevel": "Extreme", "primaryLanguages": ["Persian (Farsi)", "Azeri", "Kurdish", "Luri", "Balochi", "Arabic"], "capitalCity": "Tehran", "isIn1040Window": True,
        "activeMissionariesCount": 25, "activePrayerWarriorsCount": 6800,
        "description": "Experiencing one of the fastest-growing underground church movements in world history. Over one million former Muslims now follow Christ in secret home fellowships.",
        "prayerPoints": ["Supernatural protection for underground house church leaders and women evangelists", "Safe satellite TV, internet scripture, and VPN distribution of Bibles", "Comfort for political prisoners and martyrs' families", "Salvation of government authorities and military leaders"],
        "missionOpportunities": ["Persian Christian satellite television (SAT-7 / Mohabat TV)", "Digital discipleship and underground leadership coaching"]
    },
    {
        "id": "irq", "code": "IQ", "code3": "IRQ", "name": "Iraq", "flag": "🇮🇶", "continent": "Middle East",
        "population": 44500000,
        "dominantReligions": [{"religion": "Islam (Shia 60% / Sunni 37%)", "percentage": 97.0}, {"religion": "Christianity (Chaldean/Assyrian/Evangelical)", "percentage": 1.5}, {"religion": "Yazidi / Other", "percentage": 1.5}],
        "christianPercentage": 1.5, "evangelicalPercentage": 0.2, "unreachedPopulationPercentage": 97.8, "unreachedPeopleGroupsCount": 38,
        "securityLevel": "Extreme", "primaryLanguages": ["Arabic", "Kurdish (Sorani/Kurmanji)", "Syriac/Aramaic", "Turkmen"], "capitalCity": "Baghdad", "isIn1040Window": true,
        "activeMissionariesCount": 28, "activePrayerWarriorsCount": 1950,
        "description": "Biblical Mesopotamia (Abraham's Ur, Nineveh, Babylon). Despite decades of conflict, open doors exist in Kurdistan and Baghdad with new Arabic house churches.",
        "prayerPoints": ["Preservation and spiritual revival of ancient Christian communities in Nineveh Plains", "Church multiplication among Iraqi Kurds in Erbil and Sulaymaniyah", "Relief, healing, and Christ's hope for war-affected Yazidi and Arab youth"],
        "missionOpportunities": ["Refugee community centers and medical clinics in Erbil", "Sorani Kurdish and Iraqi Arabic media ministry"]
    },
    {
        "id": "isr", "code": "IL", "code3": "ISR", "name": "Israel", "flag": "🇮🇱", "continent": "Middle East",
        "population": 9750000,
        "dominantReligions": [{"religion": "Judaism", "percentage": 73.6}, {"religion": "Islam (Sunni)", "percentage": 18.1}, {"religion": "Christianity (Arab / Messianic Jewish)", "percentage": 1.9}, {"religion": "Druze / Other", "percentage": 6.4}],
        "christianPercentage": 1.9, "evangelicalPercentage": 0.4, "unreachedPopulationPercentage": 97.0, "unreachedPeopleGroupsCount": 16,
        "securityLevel": "Extreme", "primaryLanguages": ["Hebrew", "Arabic", "Russian", "English"], "capitalCity": "Jerusalem", "isIn1040Window": True,
        "activeMissionariesCount": 85, "activePrayerWarriorsCount": 9500,
        "description": "The Holy Land. Messianic Jewish congregations and Arab Christian churches are joining hands in reconciliation as the 'One New Man' in Christ (Ephesians 2:15).",
        "prayerPoints": ["Peace of Jerusalem (Psalm 122:6) and salvation across all Jewish and Arab families", "Unity, love, and partnership between Messianic Jewish and Arab Christian believers", "Protection for civilians from terrorism, warfare, and missile strikes"],
        "missionOpportunities": ["Hebrew and Arabic digital evangelism and apologetics", "Reconciliation prayer watch summits in Jerusalem"]
    },
    {
        "id": "jpn", "code": "JP", "code3": "JPN", "name": "Japan", "flag": "🇯🇵", "continent": "Asia",
        "population": 124500000,
        "dominantReligions": [{"religion": "Shintoism / Buddhism (Syncretic)", "percentage": 84.0}, {"religion": "Non-religious / Secular", "percentage": 14.5}, {"religion": "Christianity", "percentage": 1.5}],
        "christianPercentage": 1.5, "evangelicalPercentage": 0.5, "unreachedPopulationPercentage": 98.5, "unreachedPeopleGroupsCount": 32,
        "securityLevel": "Low", "primaryLanguages": ["Japanese"], "capitalCity": "Tokyo", "isIn1040Window": True,
        "activeMissionariesCount": 380, "activePrayerWarriorsCount": 6500,
        "description": "The second largest unreached people group in the world. Despite modern high technology, spiritual isolation is acute, with youth increasingly open to Christ.",
        "prayerPoints": ["Spiritual awakening in Tokyo and across 1,800 towns with zero churches", "Deliverance from suicide, depression, and cultural conformity", "Mobilizing the 0.5% Japanese evangelical believers for bold witness"],
        "missionOpportunities": ["Youth anime/manga Gospel arts and cafe ministry", "Bilingual church planting in Tokyo and Osaka", "Elderly care and community disaster relief"]
    },
    {
        "id": "jor", "code": "JO", "code3": "JOR", "name": "Jordan", "flag": "🇯🇴", "continent": "Middle East",
        "population": 11300000,
        "dominantReligions": [{"religion": "Islam (Sunni - Official)", "percentage": 97.2}, {"religion": "Christianity (Orthodox / Catholic / Evangelical)", "percentage": 2.1}, {"religion": "Other", "percentage": 0.7}],
        "christianPercentage": 2.1, "evangelicalPercentage": 0.4, "unreachedPopulationPercentage": 97.5, "unreachedPeopleGroupsCount": 15,
        "securityLevel": "Medium", "primaryLanguages": ["Arabic", "English"], "capitalCity": "Amman", "isIn1040Window": True,
        "activeMissionariesCount": 48, "activePrayerWarriorsCount": 1600,
        "description": "An island of relative stability in the Middle East, hosting millions of Syrian and Iraqi refugees. Jordanian churches actively minister Christ's love.",
        "prayerPoints": ["Gospel awakening among Bedouin tribes and urban youth in Amman", "Support and wisdom for churches discipling Syrian and Iraqi refugees", "Protection and fruitfulness for Christian schools and hospital outreach"],
        "missionOpportunities": ["Refugee relief and vocational training in Zaatari area", "Arabic digital discipleship"]
    },
    {
        "id": "kaz", "code": "KZ", "code3": "KAZ", "name": "Kazakhstan", "flag": "🇰🇿", "continent": "Asia",
        "population": 19600000,
        "dominantReligions": [{"religion": "Islam (Sunni)", "percentage": 70.2}, {"religion": "Christianity (Russian Orthodox)", "percentage": 24.0}, {"religion": "Christianity (Protestant/Catholic)", "percentage": 2.5}, {"religion": "Other / Atheist", "percentage": 3.3}],
        "christianPercentage": 26.5, "evangelicalPercentage": 1.2, "unreachedPopulationPercentage": 68.0, "unreachedPeopleGroupsCount": 38,
        "securityLevel": "Medium", "primaryLanguages": ["Kazakh", "Russian", "Uzbek", "Uyghur"], "capitalCity": "Astana", "isIn1040Window": True,
        "activeMissionariesCount": 65, "activePrayerWarriorsCount": 1850,
        "description": "Vast Central Asian nation where thousands of ethnic Kazakhs have come to Christ since 1991, forming vibrant indigenous fellowships across the steppe.",
        "prayerPoints": ["Multiplication of ethnic Kazakh-led house churches", "Wisdom for church leaders navigating tight state registration laws", "Sending Kazakh missionaries to Uzbekistan, Tajikistan, and Xinjiang"],
        "missionOpportunities": ["Kazakh worship and scripture media production", "University campus ministry in Almaty and Astana"]
    },
    {
        "id": "kwt", "code": "KW", "code3": "KWT", "name": "Kuwait", "flag": "🇰🇼", "continent": "Middle East",
        "population": 4800000,
        "dominantReligions": [{"religion": "Islam (Sunni 70% / Shia 30%)", "percentage": 74.6}, {"religion": "Christianity (Expat Catholic / Protestant)", "percentage": 18.2}, {"religion": "Hinduism / Other", "percentage": 7.2}],
        "christianPercentage": 18.2, "evangelicalPercentage": 2.8, "unreachedPopulationPercentage": 75.0, "unreachedPeopleGroupsCount": 14,
        "securityLevel": "Medium", "primaryLanguages": ["Arabic", "English", "Tagalog", "Hindi"], "capitalCity": "Kuwait City", "isIn1040Window": True,
        "activeMissionariesCount": 25, "activePrayerWarriorsCount": 980,
        "description": "A wealthy Gulf nation where large expatriate congregations meet openly. Secret spiritual interest among native Kuwaitis is rising through internet media.",
        "prayerPoints": ["Gospel revelation among native Kuwaiti families", "Vibrant witness of Christian domestic and corporate expatriate workers", "Protection for secret Muslim-background believers"],
        "missionOpportunities": ["Migrant domestic worker shelter and care", "Arabic smartphone scripture outreach"]
    },
    {
        "id": "kgz", "code": "KG", "code3": "KGZ", "name": "Kyrgyzstan", "flag": "🇰🇬", "continent": "Asia",
        "population": 6970000,
        "dominantReligions": [{"religion": "Islam (Sunni)", "percentage": 88.0}, {"religion": "Christianity (Russian Orthodox)", "percentage": 9.0}, {"religion": "Christianity (Protestant/Kyrgyz)", "percentage": 2.0}, {"religion": "Other", "percentage": 1.0}],
        "christianPercentage": 11.0, "evangelicalPercentage": 1.5, "unreachedPopulationPercentage": 85.0, "unreachedPeopleGroupsCount": 24,
        "securityLevel": "Medium", "primaryLanguages": ["Kyrgyz", "Russian", "Uzbek"], "capitalCity": "Bishkek", "isIn1040Window": True,
        "activeMissionariesCount": 55, "activePrayerWarriorsCount": 1400,
        "description": "Mountainous Central Asian nation with over 20,000 indigenous Kyrgyz believers. A key sending base for unreached groups across the Fergana Valley.",
        "prayerPoints": ["Boldness for Kyrgyz believers facing village ostracism in the south", "Church planting in the conservative Fergana Valley (Osh, Jalal-Abad)", "Economic opportunities to prevent youth human trafficking"],
        "missionOpportunities": ["Rural mountain village church planting", "Children's rehabilitation and sports ministry"]
    },
    {
        "id": "lao", "code": "LA", "code3": "LAO", "name": "Laos", "flag": "🇱🇦", "continent": "Asia",
        "population": 7500000,
        "dominantReligions": [{"religion": "Buddhism (Theravada)", "percentage": 66.0}, {"religion": "Animism / Folk Religion", "percentage": 30.7}, {"religion": "Christianity (Lao Evangelical)", "percentage": 2.8}, {"religion": "Other", "percentage": 0.5}],
        "christianPercentage": 2.8, "evangelicalPercentage": 2.5, "unreachedPopulationPercentage": 82.0, "unreachedPeopleGroupsCount": 118,
        "securityLevel": "Extreme", "primaryLanguages": ["Lao", "Hmong", "Khmu", "Tai"], "capitalCity": "Vientiane", "isIn1040Window": True,
        "activeMissionariesCount": 22, "activePrayerWarriorsCount": 2100,
        "description": "Despite communist state scrutiny and village persecution, the Gospel is spreading like wildfire among tribal Hmong and Khmu groups.",
        "prayerPoints": ["Perseverance for village pastors detained for their faith", "Audio Bible translation for 80+ minority languages lacking scripture", "Breakthrough among the dominant lowland Lao Buddhist majority"],
        "missionOpportunities": ["Mother-tongue audio scripture distribution", "Rural solar water wells and health clinics"]
    },
    {
        "id": "lbn", "code": "LB", "code3": "LBN", "name": "Lebanon", "flag": "🇱🇧", "continent": "Middle East",
        "population": 5500000,
        "dominantReligions": [{"religion": "Islam (Sunni/Shia/Alawite)", "percentage": 67.8}, {"religion": "Christianity (Maronite/Greek Orthodox/Evangelical)", "percentage": 32.2}],
        "christianPercentage": 32.2, "evangelicalPercentage": 1.2, "unreachedPopulationPercentage": 68.0, "unreachedPeopleGroupsCount": 12,
        "securityLevel": "Extreme", "primaryLanguages": ["Arabic", "French", "English", "Armenian"], "capitalCity": "Beirut", "isIn1040Window": True,
        "activeMissionariesCount": 95, "activePrayerWarriorsCount": 3400,
        "description": "Historic land of the Cedars. Despite economic and political collapse, Lebanese evangelical churches are demonstrating sacrificial love to thousands of refugees.",
        "prayerPoints": ["Healing from national economic collapse and freedom from political corruption", "Spiritual awakening among youth in Beirut, Tripoli, and Bekaa Valley", "Sustained support for refugee schools and food distribution centers"],
        "missionOpportunities": ["Syrian refugee education and food relief", "Arabic media production and theological training in Beirut"]
    },
    {
        "id": "mys", "code": "MY", "code3": "MYS", "name": "Malaysia", "flag": "🇲🇾", "continent": "Asia",
        "population": 33900000,
        "dominantReligions": [{"religion": "Islam (Sunni - Official)", "percentage": 63.5}, {"religion": "Buddhism", "percentage": 18.7}, {"religion": "Christianity", "percentage": 9.1}, {"religion": "Hinduism", "percentage": 6.3}, {"religion": "Other", "percentage": 2.4}],
        "christianPercentage": 9.1, "evangelicalPercentage": 4.5, "unreachedPopulationPercentage": 64.0, "unreachedPeopleGroupsCount": 154,
        "securityLevel": "High", "primaryLanguages": ["Malay (Bahasa Melayu)", "English", "Mandarin", "Tamil", "Iban", "Kadazan"], "capitalCity": "Kuala Lumpur", "isIn1040Window": True,
        "activeMissionariesCount": 140, "activePrayerWarriorsCount": 4100,
        "description": "Constitutionally, all ethnic Malays are defined as Muslim and forbidden to convert. Vibrant churches exist among Chinese, Indian, and East Malaysian indigenous tribes.",
        "prayerPoints": ["Gospel breakthrough and religious freedom for 20 million ethnic Malays", "Revival and missionary zeal in East Malaysia (Sabah and Sarawak)", "Courage and legal protection for secret Malay believers"],
        "missionOpportunities": ["Indigenous Orang Asli rainforest village ministry", "Digital discipleship and Christian literature"]
    },
    {
        "id": "mdv", "code": "MV", "code3": "MDV", "name": "Maldives", "flag": "🇲🇻", "continent": "Asia",
        "population": 520000,
        "dominantReligions": [{"religion": "Islam (Sunni - 100% Official Requirement)", "percentage": 99.9}, {"religion": "Christianity (Expat / Secret)", "percentage": 0.1}],
        "christianPercentage": 0.1, "evangelicalPercentage": 0.05, "unreachedPopulationPercentage": 99.9, "unreachedPeopleGroupsCount": 4,
        "securityLevel": "Extreme", "primaryLanguages": ["Dhivehi", "English", "Arabic"], "capitalCity": "Malé", "isIn1040Window": True,
        "activeMissionariesCount": 2, "activePrayerWarriorsCount": 650,
        "description": "Archipelago where citizenship legally requires being Muslim. Carrying a Bible or converting brings severe penalties, yet a secret handful of believers worship Christ.",
        "prayerPoints": ["Supernatural protection and growth for secret Maldivian believers", "Opening of the islands to religious freedom and human rights", "Dhivehi audio scripture and digital broadcasting penetration"],
        "missionOpportunities": ["Dhivehi language digital media and shortwave radio", "Expat resort worker Christian witness"]
    },
    {
        "id": "mng", "code": "MN", "code3": "MNG", "name": "Mongolia", "flag": "🇲🇳", "continent": "Asia",
        "population": 3450000,
        "dominantReligions": [{"religion": "Buddhism (Tibetan)", "percentage": 53.0}, {"religion": "Atheist / Non-religious", "percentage": 38.6}, {"religion": "Islam (Kazakh)", "percentage": 3.0}, {"religion": "Christianity", "percentage": 2.3}, {"religion": "Shamanism", "percentage": 3.1}],
        "christianPercentage": 2.3, "evangelicalPercentage": 2.0, "unreachedPopulationPercentage": 92.0, "unreachedPeopleGroupsCount": 7,
        "securityLevel": "Low", "primaryLanguages": ["Mongolian", "Kazakh"], "capitalCity": "Ulaanbaatar", "isIn1040Window: true": True,
        "activeMissionariesCount": 60, "activePrayerWarriorsCount": 1600,
        "description": "Virtually zero Christians existed in 1990; today over 60,000 vibrant believers worship in hundreds of churches. Actively sending missionaries to Siberia and Central Asia.",
        "prayerPoints": ["Discipleship depth and pastoral training for first-generation church leaders", "Reaching nomadic herder families across the Gobi Desert and northern steppes", "Awakening among Muslim Kazakhs in western Bayan-Ölgii province"],
        "missionOpportunities": ["Steppe nomad solar audio Bible distribution", "Addiction recovery centers in Ulaanbaatar"]
    },
    {
        "id": "mmr", "code": "MM", "code3": "MMR", "name": "Myanmar", "flag": "🇲🇲", "continent": "Asia",
        "population": 54200000,
        "dominantReligions": [{"religion": "Buddhism (Theravada)", "percentage": 87.9}, {"religion": "Christianity (Baptist/Catholic/Pentecostal)", "percentage": 6.2}, {"religion": "Islam", "percentage": 4.3}, {"religion": "Animism/Other", "percentage": 1.6}],
        "christianPercentage": 6.2, "evangelicalPercentage": 4.8, "unreachedPopulationPercentage": 88.0, "unreachedPeopleGroupsCount": 98,
        "securityLevel": "Extreme", "primaryLanguages": ["Burmese", "Shan", "Karen", "Kachin", "Chin"], "capitalCity": "Naypyidaw", "isIn1040Window": True,
        "activeMissionariesCount": 120, "activePrayerWarriorsCount": 4200,
        "description": "First reached by Adoniram Judson in 1813. Today, despite civil military conflict, believers in Karen, Kachin, and Chin hills courageously shine Christ's light.",
        "prayerPoints": ["End to military violence, civil war, and displacement of innocent civilians", "Spiritual awakening among the 35 million Bamar Buddhist majority", "Relief and trauma healing for thousands in refugee camps"],
        "missionOpportunities": ["Displaced persons camp relief and trauma care", "Monastery dialogue and Buddhist outreach"]
    },
    {
        "id": "npl", "code": "NP", "code3": "NPL", "name": "Nepal", "flag": "🇳🇵", "continent": "Asia",
        "population": 30500000,
        "dominantReligions": [{"religion": "Hinduism", "percentage": 81.3}, {"religion": "Buddhism", "percentage": 9.0}, {"religion": "Islam", "percentage": 4.4}, {"religion": "Christianity", "percentage": 3.0}, {"religion": "Kirat / Other", "percentage": 2.3}],
        "christianPercentage": 3.0, "evangelicalPercentage": 2.8, "unreachedPopulationPercentage": 92.0, "unreachedPeopleGroupsCount": 265,
        "securityLevel": "High", "primaryLanguages": ["Nepali", "Maithili", "Bhojpuri", "Tharu", "Tamang", "Newari"], "capitalCity": "Kathmandu", "isIn1040Window": True,
        "activeMissionariesCount": 140, "activePrayerWarriorsCount": 3900,
        "description": "Former Hindu kingdom witnessing explosive church growth over the past three decades. Nepali evangelists are planting churches in remote Himalayan peaks.",
        "prayerPoints": ["Multiplication of house churches in high Himalayan valleys", "Protection for pastors under strict anti-conversion laws", "Reaching unreached Terai plains Hindu castes (Maithili, Bhojpuri)"],
        "missionOpportunities": ["Remote mountain trekking medical missions", "Anti-human-trafficking border intercepts and rehabilitation"]
    },
    {
        "id": "prk", "code": "KP", "code3": "PRK", "name": "North Korea", "flag": "🇰🇵", "continent": "Asia",
        "population": 26000000,
        "dominantReligions": [{"religion": "Juche / State Atheism", "percentage": 99.0}, {"religion": "Christianity (Underground)", "percentage": 1.0}],
        "christianPercentage": 1.0, "evangelicalPercentage": 0.8, "unreachedPopulationPercentage": 99.2, "unreachedPeopleGroupsCount": 6,
        "securityLevel": "Extreme", "primaryLanguages": ["Korean"], "capitalCity": "Pyongyang", "isIn1040Window": True,
        "activeMissionariesCount": 5, "activePrayerWarriorsCount": 14000,
        "description": "Pyongyang was once called the 'Jerusalem of the East' (1907 Revival). Today estimated 300,000+ underground Christians endure extreme totalitarian persecution.",
        "prayerPoints": ["Sustained supernatural strength for underground believers in labor camps", "Collapse of totalitarian spiritual oppression and freedom to preach Jesus", "Radio, balloon, and SD card gospel broadcasts reaching hungry citizens"],
        "missionOpportunities": ["Cross-border radio broadcasting (FEBC / TWR)", "North Korean defector discipleship in South Korea"]
    },
    {
        "id": "omn", "code": "OM", "code3": "OMN", "name": "Oman", "flag": "🇴🇲", "continent": "Middle East",
        "population": 4600000,
        "dominantReligions": [{"religion": "Islam (Ibadi 45% / Sunni 45%)", "percentage": 85.9}, {"religion": "Christianity (Expat)", "percentage": 6.5}, {"religion": "Hinduism", "percentage": 5.5}, {"religion": "Other", "percentage": 2.1}],
        "christianPercentage": 6.5, "evangelicalPercentage": 1.1, "unreachedPopulationPercentage": 87.0, "unreachedPeopleGroupsCount": 16,
        "securityLevel": "Medium", "primaryLanguages": ["Arabic", "English", "Balochi", "Shehri (Jibbali)"], "capitalCity": "Muscat", "isIn1040Window": True,
        "activeMissionariesCount": 24, "activePrayerWarriorsCount": 980,
        "description": "Known for peaceful diplomacy and tolerance toward expatriate churches. The indigenous Omani Arabs and southern Dhofar mountain tribes remain unreached.",
        "prayerPoints": ["Salvation of Omani youth and royal leadership", "Gospel breakthrough among southern Shehri and Mehri mountain tribes", "Witness of expatriate Christian professionals in Muscat and Salalah"],
        "missionOpportunities": ["Professional business-as-mission start-ups", "Dhofar dialect Bible translation"]
    },
    {
        "id": "pak", "code": "PK", "code3": "PAK", "name": "Pakistan", "flag": "🇵🇰", "continent": "Asia",
        "population": 240500000,
        "dominantReligions": [{"religion": "Islam (Sunni 85% / Shia 12%)", "percentage": 96.5}, {"religion": "Christianity", "percentage": 1.6}, {"religion": "Hinduism", "percentage": 1.6}, {"religion": "Other", "percentage": 0.3}],
        "christianPercentage": 1.6, "evangelicalPercentage": 0.6, "unreachedPopulationPercentage": 97.9, "unreachedPeopleGroupsCount": 425,
        "securityLevel": "Extreme", "primaryLanguages": ["Urdu", "Punjabi", "Pashto", "Sindhi", "Saraiki", "Balochi"], "capitalCity": "Islamabad", "isIn1040Window": True,
        "activeMissionariesCount": 110, "activePrayerWarriorsCount": 6500,
        "description": "Second largest Muslim nation in the world. Pakistani believers show extraordinary courage amidst blasphemy law threats and brick-kiln bonded labor.",
        "prayerPoints": ["Deliverance of Christian families from bonded slavery in brick kilns", "Protection against blasphemy accusations and forced conversions", "Gospel movements among Pashtun, Sindhi, and Baloch unreached peoples"],
        "missionOpportunities": ["Brick kiln bonded laborer redemption and schools", "Urdu digital satellite media broadcasting"]
    },
    {
        "id": "pse", "code": "PS", "code3": "PSE", "name": "Palestine", "flag": "🇵🇸", "continent": "Middle East",
        "population": 5250000,
        "dominantReligions": [{"religion": "Islam (Sunni)", "percentage": 98.0}, {"religion": "Christianity (Greek Orthodox/Catholic/Evangelical)", "percentage": 1.5}, {"religion": "Other", "percentage": 0.5}],
        "christianPercentage": 1.5, "evangelicalPercentage": 0.2, "unreachedPopulationPercentage": 98.5, "unreachedPeopleGroupsCount": 4,
        "securityLevel": "Extreme", "primaryLanguages": ["Arabic", "English"], "capitalCity": "Ramallah / East Jerusalem", "isIn1040Window": True,
        "activeMissionariesCount": 20, "activePrayerWarriorsCount": 1800,
        "description": "Home to historic biblical sites (Bethlehem, Nazareth, Hebron). Palestinian evangelical believers courageously model Christ's peace and reconciliation.",
        "prayerPoints": ["Healing and comfort for families suffering devastating war and loss in Gaza and West Bank", "Strengthening the small faithful Christian community in Bethlehem and Ramallah", "Supernatural encounters with Jesus for Muslim and Jewish seekers"],
        "missionOpportunities": ["Emergency humanitarian food and medical relief", "Trauma therapy and Christian youth education in Bethlehem"]
    },
    {
        "id": "phl", "code": "PH", "code3": "PHL", "name": "Philippines", "flag": "🇵🇭", "continent": "Asia",
        "population": 115600000,
        "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 78.8}, {"religion": "Christianity (Evangelical/Protestant)", "percentage": 12.5}, {"religion": "Islam (Bangsamoro)", "percentage": 6.4}, {"religion": "Other", "percentage": 2.3}],
        "christianPercentage": 91.3, "evangelicalPercentage": 12.5, "unreachedPopulationPercentage": 8.0, "unreachedPeopleGroupsCount": 38,
        "securityLevel": "Low", "primaryLanguages": ["Filipino (Tagalog)", "English", "Cebuano", "Ilocano", "Maranao", "Tausug"], "capitalCity": "Manila", "isIn1040Window": True,
        "activeMissionariesCount": 480, "activePrayerWarriorsCount": 9800,
        "description": "A premier missionary sending nation in Asia. Filipino overseas workers (OFWs) serve as marketplace missionaries across the Middle East, while home churches reach Muslim Mindanao.",
        "prayerPoints": ["Gospel movements among Muslim Maranao, Maguindanao, and Tausug in Mindanao", "Empowering 10+ million Overseas Filipino Workers as kingdom ambassadors", "Righteous governance, economic justice, and disaster resilience"],
        "missionOpportunities": ["Mindanao peacebuilding and church planting", "Tribal Bible translation in mountain interiors", "OFW pre-departure mission training"]
    },
    {
        "id": "qat", "code": "QA", "code3": "QAT", "name": "Qatar", "flag": "🇶🇦", "continent": "Middle East",
        "population": 2980000,
        "dominantReligions": [{"religion": "Islam (Sunni - Official)", "percentage": 65.2}, {"religion": "Christianity (Expat Catholic/Protestant)", "percentage": 15.4}, {"religion": "Hinduism", "percentage": 14.2}, {"religion": "Other", "percentage": 5.2}],
        "christianPercentage": 15.4, "evangelicalPercentage": 2.2, "unreachedPopulationPercentage": 67.0, "unreachedPeopleGroupsCount": 12,
        "securityLevel": "Medium", "primaryLanguages": ["Arabic", "English", "Hindi", "Tagalog"], "capitalCity": "Doha", "isIn1040Window": True,
        "activeMissionariesCount": 18, "activePrayerWarriorsCount": 860,
        "description": "Rapidly modernized Gulf peninsula where expatriate church complexes worship freely. Spiritual hunger is growing among native Qatari youth.",
        "prayerPoints": ["Breakthrough and dreams of Jesus among native Qatari citizens", "Spiritual protection and vitality for migrant construction and service workers", "Unity in the multi-national Church City in Doha"],
        "missionOpportunities": ["Migrant worker chaplaincy and care", "Arabic smartphone scripture outreach"]
    },
    {
        "id": "sau", "code": "SA", "code3": "SAU", "name": "Saudi Arabia", "flag": "🇸🇦", "continent": "Middle East",
        "population": 36400000,
        "dominantReligions": [{"religion": "Islam (Sunni 85% / Shia 15% - Official)", "percentage": 93.0}, {"religion": "Christianity (Expatriate)", "percentage": 4.5}, {"religion": "Other", "percentage": 2.5}],
        "christianPercentage": 4.5, "evangelicalPercentage": 1.2, "unreachedPopulationPercentage": 94.0, "unreachedPeopleGroupsCount": 35,
        "securityLevel": "Extreme", "primaryLanguages": ["Arabic (Najdi/Hejazi)", "English", "Tagalog", "Urdu"], "capitalCity": "Riyadh", "isIn1040Window": True,
        "activeMissionariesCount": 15, "activePrayerWarriorsCount": 5400,
        "description": "Heartland of Islam containing Mecca and Medina. Experiencing rapid social modernization, with unprecedented numbers of Saudis quietly encountering Christ via internet and dreams.",
        "prayerPoints": ["Multiplication of secret underground Saudi home fellowships in Riyadh, Jeddah, and Dammam", "Boldness for foreign Christian doctors, nurses, and engineers sharing their faith", "True spiritual liberty for Saudi women and youth searching for hope"],
        "missionOpportunities": ["Digital evangelism in Saudi dialects", "Expatriate professional workplace witness"]
    },
    {
        "id": "sgp", "code": "SG", "code3": "SGP", "name": "Singapore", "flag": "🇸🇬", "continent": "Asia",
        "population": 5900000,
        "dominantReligions": [{"religion": "Buddhism / Taoism", "percentage": 40.0}, {"religion": "Christianity (Protestant/Catholic)", "percentage": 18.9}, {"religion": "Islam (Malay)", "percentage": 15.6}, {"religion": "No Religion / Secular", "percentage": 20.0}, {"religion": "Hinduism", "percentage": 5.0}],
        "christianPercentage": 18.9, "evangelicalPercentage": 8.5, "unreachedPopulationPercentage": 18.0, "unreachedPeopleGroupsCount": 8,
        "securityLevel": "Low", "primaryLanguages": ["English", "Mandarin", "Malay", "Tamil"], "capitalCity": "Singapore", "isIn1040Window": True,
        "activeMissionariesCount": 320, "activePrayerWarriorsCount": 6200,
        "description": "The 'Antioch of Asia.' A major strategic financial and missional hub funding and sending thousands of missionaries across the 10/40 window.",
        "prayerPoints": ["Maintaining spiritual passion against intense materialism and careerism", "Mobilizing young professionals as marketplace missionaries across Asia", "Reaching the large migrant construction worker population"],
        "missionOpportunities": ["Regional mission training and finance hubs", "South Asian migrant worker fellowship centers"]
    },
    {
        "id": "kor", "code": "KR", "code3": "KOR", "name": "South Korea", "flag": "🇰🇷", "continent": "Asia",
        "population": 51700000,
        "dominantReligions": [{"religion": "No Religion / Secular", "percentage": 50.0}, {"religion": "Christianity (Protestant)", "percentage": 20.0}, {"religion": "Christianity (Catholic)", "percentage": 8.0}, {"religion": "Buddhism", "percentage": 21.0}, {"religion": "Other", "percentage": 1.0}],
        "christianPercentage": 28.0, "evangelicalPercentage": 16.5, "unreachedPopulationPercentage": 2.0, "unreachedPeopleGroupsCount": 4,
        "securityLevel": "Low", "primaryLanguages": ["Korean", "English"], "capitalCity": "Seoul", "isIn1040Window": False,
        "activeMissionariesCount": 980, "activePrayerWarriorsCount": 16500,
        "description": "One of the world's greatest missionary senders (over 22,000 sent globally), famous for early morning prayer and prayer mountains.",
        "prayerPoints": ["Revival of first love and early morning prayer among younger generations", "Peace, reunification, and Gospel penetration into North Korea", "Continued missionary mobilization to the Islamic and Buddhist worlds"],
        "missionOpportunities": ["Global missionary training centers in Seoul", "North Korean defector discipleship and trauma care"]
    },
    {
        "id": "lka", "code": "LK", "code3": "LKA", "name": "Sri Lanka", "flag": "🇱🇰", "continent": "Asia",
        "population": 22200000,
        "dominantReligions": [{"religion": "Buddhism (Theravada)", "percentage": 70.2}, {"religion": "Hinduism (Tamil)", "percentage": 12.6}, {"religion": "Islam (Moor)", "percentage": 9.7}, {"religion": "Christianity (Catholic/Evangelical)", "percentage": 7.5}],
        "christianPercentage": 7.5, "evangelicalPercentage": 1.5, "unreachedPopulationPercentage": 82.0, "unreachedPeopleGroupsCount": 28,
        "securityLevel": "Medium", "primaryLanguages": ["Sinhala", "Tamil", "English"], "capitalCity": "Colombo (Sri Jayawardenepura)", "isIn1040Window": True,
        "activeMissionariesCount": 68, "activePrayerWarriorsCount": 1900,
        "description": "The 'Pearl of the Indian Ocean.' Despite civil war scars and economic crises, vibrant church planting movements unite Sinhalese and Tamil believers.",
        "prayerPoints": ["Economic restoration, ethical leadership, and eradication of corruption", "Courage for rural pastors facing local religious harassment", "Gospel breakthrough among Sri Lankan Moors and rural tea plantation Tamils"],
        "missionOpportunities": ["Tea estate community development and education", "Bilingual youth sports and media camps"]
    },
    {
        "id": "syr", "code": "SY", "code3": "SYR", "name": "Syria", "flag": "🇸🇾", "continent": "Middle East",
        "population": 22100000,
        "dominantReligions": [{"religion": "Islam (Sunni 74% / Alawite 13%)", "percentage": 90.0}, {"religion": "Christianity (Orthodox/Catholic/Evangelical)", "percentage": 7.0}, {"religion": "Druze", "percentage": 3.0}],
        "christianPercentage": 7.0, "evangelicalPercentage": 0.4, "unreachedPopulationPercentage": 92.5, "unreachedPeopleGroupsCount": 24,
        "securityLevel": "Extreme", "primaryLanguages": ["Arabic", "Kurdish", "Syriac/Aramaic", "Armenian"], "capitalCity": "Damascus", "isIn1040Window": True,
        "activeMissionariesCount": 22, "activePrayerWarriorsCount": 3100,
        "description": "Where Saul became Paul on the Damascus road. Despite devastating civil war and destruction, local evangelical churches have become beacons of hope and love.",
        "prayerPoints": ["Total restoration of peace and return of displaced families", "Spiritual protection and renewal for pastors ministering in ruined cities", "Supernatural harvest among Muslim seekers served by Christian food relief"],
        "missionOpportunities": ["Emergency food, heating, and medical distribution", "Trauma healing and children's education centers in Aleppo and Damascus"]
    },
    {
        "id": "tjk", "code": "TJ", "code3": "TJK", "name": "Tajikistan", "flag": "🇹🇯", "continent": "Asia",
        "population": 10100000,
        "dominantReligions": [{"religion": "Islam (Sunni 95% / Ismaili Shia 3%)", "percentage": 98.0}, {"religion": "Christianity (Russian Orthodox/Tajik)", "percentage": 1.2}, {"religion": "Other", "percentage": 0.8}],
        "christianPercentage": 1.2, "evangelicalPercentage": 0.1, "unreachedPopulationPercentage": 98.5, "unreachedPeopleGroupsCount": 26,
        "securityLevel": "Extreme", "primaryLanguages": ["Tajik (Persian dialect)", "Russian", "Pamir Languages"], "capitalCity": "Dushanbe", "isIn1040Window": True,
        "activeMissionariesCount": 16, "activePrayerWarriorsCount": 950,
        "description": "High Pamir mountain nation. Converts from Islam face heavy government scrutiny and family pressure, yet a resilient body of believers continues to grow.",
        "prayerPoints": ["Protection for unregistered house churches in Dushanbe and Khujand", "Breakthrough among the Pamiri Ismaili mountain peoples", "Translation and printing of scripture in local Pamir dialects"],
        "missionOpportunities": ["Pamir mountain community development and English schools", "Digital Tajiki audio Bible distribution"]
    },
    {
        "id": "tha", "code": "TH", "code3": "THA", "name": "Thailand", "flag": "🇹🇭", "continent": "Asia",
        "population": 71800000,
        "dominantReligions": [{"religion": "Buddhism (Theravada)", "percentage": 93.5}, {"religion": "Islam (Malay southern)", "percentage": 5.4}, {"religion": "Christianity", "percentage": 1.1}],
        "christianPercentage": 1.1, "evangelicalPercentage": 0.7, "unreachedPopulationPercentage": 98.5, "unreachedPeopleGroupsCount": 115,
        "securityLevel": "Low", "primaryLanguages": ["Thai (Central)", "Isan", "Northern Thai", "Southern Thai", "Malay (Patani)"], "capitalCity": "Bangkok", "isIn1040Window": True,
        "activeMissionariesCount": 260, "activePrayerWarriorsCount": 4800,
        "description": "The 'Land of Smiles.' Never colonized. Today native Thai church planting movements (e.g. Free in Christ) are baptizing thousands in rural Isan provinces.",
        "prayerPoints": ["Breakthrough in 70,000 villages with zero Christian witness", "Multiplying church planting movements in northeastern Isan", "Deliverance of youth from the commercial sex trade in tourist cities"],
        "missionOpportunities": ["Anti-trafficking rescue and restoration homes in Bangkok and Pattaya", "Isan rural farming church planting"]
    },
    {
        "id": "tls", "code": "TL", "code3": "TLS", "name": "Timor-Leste", "flag": "🇹🇱", "continent": "Asia",
        "population": 1340000,
        "dominantReligions": [{"religion": "Christianity (Catholic)", "percentage": 97.5}, {"religion": "Christianity (Protestant)", "percentage": 1.9}, {"religion": "Islam / Traditional", "percentage": 0.6}],
        "christianPercentage": 99.4, "evangelicalPercentage": 2.2, "unreachedPopulationPercentage": 3.0, "unreachedPeopleGroupsCount": 2,
        "securityLevel": "Low", "primaryLanguages": ["Tetum", "Portuguese", "Indonesian"], "capitalCity": "Dili", "isIn1040Window": False,
        "activeMissionariesCount": 25, "activePrayerWarriorsCount": 540,
        "description": "Asia's newest nation, predominantly Catholic with growing evangelical fellowships focused on youth discipleship and community development.",
        "prayerPoints": ["Deliverance from animistic spirit veneration and syncretism", "Empowering youth with vocational skills and biblical leadership", "National reconciliation and righteous governance"],
        "missionOpportunities": ["Youth vocational institutes and English academies in Dili", "Rural community health clinics"]
    },
    {
        "id": "tur", "code": "TR", "code3": "TUR", "name": "Turkey", "flag": "🇹🇷", "continent": "Middle East",
        "population": 85300000,
        "dominantReligions": [{"religion": "Islam (Sunni/Alevi)", "percentage": 98.2}, {"religion": "Christianity", "percentage": 0.2}, {"religion": "Agnostic / Secular", "percentage": 1.6}],
        "christianPercentage": 0.2, "evangelicalPercentage": 0.05, "unreachedPopulationPercentage": 96.5, "unreachedPeopleGroupsCount": 54,
        "securityLevel": "Medium", "primaryLanguages": ["Turkish", "Kurdish (Kurmanji)", "Zaza", "Arabic"], "capitalCity": "Ankara", "isIn1040Window": True,
        "activeMissionariesCount": 165, "activePrayerWarriorsCount": 3200,
        "description": "The biblical land of the Seven Churches of Revelation and Antioch. Today over 80 million people remain unreached, though youth spiritual hunger is rising.",
        "prayerPoints": ["Revival in historic biblical cities (Ephesus, Smyrna, Antioch)", "Fruitful church planting among Kurdish and Turkish urban youth", "Open doors for legal church building recognition"],
        "missionOpportunities": ["University student ministry in Istanbul and Ankara", "Christian publishing, cafes, and business as mission"]
    },
    {
        "id": "tkm", "code": "TM", "code3": "TKM", "name": "Turkmenistan", "flag": "🇹🇲", "continent": "Asia",
        "population": 6500000,
        "dominantReligions": [{"religion": "Islam (Sunni)", "percentage": 93.0}, {"religion": "Christianity (Russian Orthodox)", "percentage": 5.0}, {"religion": "Christianity (Turkmen Underground)", "percentage": 0.5}, {"religion": "Other", "percentage": 1.5}],
        "christianPercentage": 5.5, "evangelicalPercentage": 0.2, "unreachedPopulationPercentage": 94.0, "unreachedPeopleGroupsCount": 16,
        "securityLevel": "Extreme", "primaryLanguages": ["Turkmen", "Russian", "Uzbek"], "capitalCity": "Ashgabat", "isIn1040Window": True,
        "activeMissionariesCount": 6, "activePrayerWarriorsCount": 820,
        "description": "One of the most closed and secretive nations in the world. Underground Turkmen believers gather secretly in homes under strict surveillance.",
        "prayerPoints": ["Supernatural protection for isolated underground Turkmen believers", "Opening of the nation to religious freedom and international Bibles", "Radio and internet broadcasts reaching remote desert towns"],
        "missionOpportunities": ["Turkmen digital media and satellite broadcasting", "Refugee diaspora outreach in Turkey and Europe"]
    },
    {
        "id": "are", "code": "AE", "code3": "ARE", "name": "United Arab Emirates", "flag": "🇦🇪", "continent": "Middle East",
        "population": 9900000,
        "dominantReligions": [{"religion": "Islam (Official)", "percentage": 76.0}, {"religion": "Christianity (Expatriate)", "percentage": 12.6}, {"religion": "Hinduism", "percentage": 6.6}, {"religion": "Other", "percentage": 4.8}],
        "christianPercentage": 12.6, "evangelicalPercentage": 2.4, "unreachedPopulationPercentage": 78.0, "unreachedPeopleGroupsCount": 25,
        "securityLevel": "Medium", "primaryLanguages": ["Arabic", "English", "Hindi", "Tagalog", "Urdu"], "capitalCity": "Abu Dhabi", "isIn1040Window": True,
        "activeMissionariesCount": 55, "activePrayerWarriorsCount": 1800,
        "description": "Global commercial crossroads (Dubai). While 88% of residents are foreign expatriates who worship in large churches, native Emirati Arabs remain largely unreached.",
        "prayerPoints": ["Gospel awakening among native Emirati families and ruling officials", "Boldness and holiness for the 1M+ expatriate Christians living in Dubai and Abu Dhabi", "Justice and care for migrant construction and domestic workers"],
        "missionOpportunities": ["Marketplace ministry in international corporations", "Expat migrant worker care and outreach"]
    },
    {
        "id": "uzb", "code": "UZ", "code3": "UZB", "name": "Uzbekistan", "flag": "🇺🇿", "continent": "Asia",
        "population": 36000000,
        "dominantReligions": [{"religion": "Islam (Sunni)", "percentage": 88.0}, {"religion": "Christianity (Russian Orthodox)", "percentage": 9.0}, {"religion": "Christianity (Uzbek Evangelical)", "percentage": 1.5}, {"religion": "Other", "percentage": 1.5}],
        "christianPercentage": 10.5, "evangelicalPercentage": 0.8, "unreachedPopulationPercentage": 89.0, "unreachedPeopleGroupsCount": 32,
        "securityLevel": "High", "primaryLanguages": ["Uzbek", "Russian", "Tajik", "Karakalpak"], "capitalCity": "Tashkent", "isIn1040Window": True,
        "activeMissionariesCount": 42, "activePrayerWarriorsCount": 1950,
        "description": "Heart of the ancient Silk Road (Samarkand, Bukhara). Over 30,000 indigenous Uzbeks follow Christ today, actively planting house churches.",
        "prayerPoints": ["Freedom to print and distribute Uzbek Bibles without government confiscation", "Church multiplication in conservative Fergana Valley and Karakalpakstan", "Protection for rural converts from clan harassment"],
        "missionOpportunities": ["Uzbek audio/digital discipleship", "Business as mission and vocational academies"]
    },
    {
        "id": "vnm", "code": "VN", "code3": "VNM", "name": "Vietnam", "flag": "🇻🇳", "continent": "Asia",
        "population": 99500000,
        "dominantReligions": [{"religion": "Folk Religion / Non-religious", "percentage": 73.0}, {"religion": "Buddhism", "percentage": 14.9}, {"religion": "Christianity (Catholic)", "percentage": 7.0}, {"religion": "Christianity (Protestant/Montagnard/Hmong)", "percentage": 2.5}, {"religion": "Cao Dai / Other", "percentage": 2.6}],
        "christianPercentage": 9.5, "evangelicalPercentage": 2.5, "unreachedPopulationPercentage": 85.0, "unreachedPeopleGroupsCount": 78,
        "securityLevel": "High", "primaryLanguages": ["Vietnamese", "Hmong", "Tay", "Jarai", "Bahnar"], "capitalCity": "Hanoi", "isIn1040Window": True,
        "activeMissionariesCount": 110, "activePrayerWarriorsCount": 4100,
        "description": "Witnessing rapid church multiplication among ethnic minority Montagnards and Hmong in the Central Highlands, with urban house churches rising in Ho Chi Minh City.",
        "prayerPoints": ["Full religious freedom and end to village land confiscations of believers", "Gospel breakthrough among the 85 million ethnic Kinh (Vietnamese) majority", "Leadership training for thousands of new rural pastors"],
        "missionOpportunities": ["Montagnard mother-tongue audio scripture distribution", "Urban marketplace discipleship in Saigon and Hanoi"]
    },
    {
        "id": "yem", "code": "YE", "code3": "YEM", "name": "Yemen", "flag": "🇾🇪", "continent": "Middle East",
        "population": 33700000,
        "dominantReligions": [{"religion": "Islam (Sunni)", "percentage": 65.0}, {"religion": "Islam (Zaydi Shia)", "percentage": 34.5}, {"religion": "Christianity", "percentage": 0.08}, {"religion": "Other", "percentage": 0.42}],
        "christianPercentage": 0.08, "evangelicalPercentage": 0.05, "unreachedPopulationPercentage": 99.6, "unreachedPeopleGroupsCount": 29,
        "securityLevel": "Extreme", "primaryLanguages": ["Arabic (Yemeni)", "Mehri", "Soqotri"], "capitalCity": "Sana'a", "isIn1040Window": True,
        "activeMissionariesCount": 8, "activePrayerWarriorsCount": 1420,
        "description": "Southern Arabian Peninsula. Despite acute famine and conflict, unprecedented numbers of Yemenis are seeking truth via digital scripture and visions.",
        "prayerPoints": ["Sustenance and gospel breakthroughs amidst severe humanitarian crisis", "Supernatural protection for secret Yemeni converts to Christ", "Bible translation completion in Mehri and Soqotri dialects"],
        "missionOpportunities": ["Digital discipleship and online Arabic prayer rooms", "Famine relief and clean water gospel initiatives"]
    }
]

print(f"Loaded {len(countries)} sample Asian/Middle East countries in base script.")
